// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import aaveOracleAbiJson from './aaveOracleAbi.json';

export const aaveOracleAbi = aaveOracleAbiJson as unknown as readonly [
  {
    readonly inputs: readonly [
      {
        readonly internalType: 'contract IPoolAddressesProvider';
        readonly name: 'provider';
        readonly type: 'address';
      },
      { readonly internalType: 'address[]'; readonly name: 'assets'; readonly type: 'address[]' },
      { readonly internalType: 'address[]'; readonly name: 'sources'; readonly type: 'address[]' },
      {
        readonly internalType: 'address';
        readonly name: 'fallbackOracle';
        readonly type: 'address';
      },
      { readonly internalType: 'address'; readonly name: 'baseCurrency'; readonly type: 'address' },
      {
        readonly internalType: 'uint256';
        readonly name: 'baseCurrencyUnit';
        readonly type: 'uint256';
      },
    ];
    readonly stateMutability: 'nonpayable';
    readonly type: 'constructor';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'asset';
        readonly type: 'address';
      },
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'source';
        readonly type: 'address';
      },
    ];
    readonly name: 'AssetSourceUpdated';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'baseCurrency';
        readonly type: 'address';
      },
      {
        readonly indexed: false;
        readonly internalType: 'uint256';
        readonly name: 'baseCurrencyUnit';
        readonly type: 'uint256';
      },
    ];
    readonly name: 'BaseCurrencySet';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'fallbackOracle';
        readonly type: 'address';
      },
    ];
    readonly name: 'FallbackOracleUpdated';
    readonly type: 'event';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'ADDRESSES_PROVIDER';
    readonly outputs: readonly [
      {
        readonly internalType: 'contract IPoolAddressesProvider';
        readonly name: '';
        readonly type: 'address';
      },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'BASE_CURRENCY';
    readonly outputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'BASE_CURRENCY_UNIT';
    readonly outputs: readonly [
      { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'asset'; readonly type: 'address' },
    ];
    readonly name: 'getAssetPrice';
    readonly outputs: readonly [
      { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address[]'; readonly name: 'assets'; readonly type: 'address[]' },
    ];
    readonly name: 'getAssetsPrices';
    readonly outputs: readonly [
      { readonly internalType: 'uint256[]'; readonly name: ''; readonly type: 'uint256[]' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'getFallbackOracle';
    readonly outputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'asset'; readonly type: 'address' },
    ];
    readonly name: 'getSourceOfAsset';
    readonly outputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address[]'; readonly name: 'assets'; readonly type: 'address[]' },
      { readonly internalType: 'address[]'; readonly name: 'sources'; readonly type: 'address[]' },
    ];
    readonly name: 'setAssetSources';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: 'address';
        readonly name: 'fallbackOracle';
        readonly type: 'address';
      },
    ];
    readonly name: 'setFallbackOracle';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
] satisfies Abi;
