// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import defaultReserveInterestRateStrategyAbiJson from './defaultReserveInterestRateStrategyAbi.json';

export const defaultReserveInterestRateStrategyAbi =
  defaultReserveInterestRateStrategyAbiJson as unknown as readonly [
    {
      readonly inputs: readonly [
        {
          readonly internalType: 'contract IPoolAddressesProvider';
          readonly name: 'provider';
          readonly type: 'address';
        },
        {
          readonly internalType: 'uint256';
          readonly name: 'optimalUsageRatio';
          readonly type: 'uint256';
        },
        {
          readonly internalType: 'uint256';
          readonly name: 'baseVariableBorrowRate';
          readonly type: 'uint256';
        },
        {
          readonly internalType: 'uint256';
          readonly name: 'variableRateSlope1';
          readonly type: 'uint256';
        },
        {
          readonly internalType: 'uint256';
          readonly name: 'variableRateSlope2';
          readonly type: 'uint256';
        },
        {
          readonly internalType: 'uint256';
          readonly name: 'stableRateSlope1';
          readonly type: 'uint256';
        },
        {
          readonly internalType: 'uint256';
          readonly name: 'stableRateSlope2';
          readonly type: 'uint256';
        },
        {
          readonly internalType: 'uint256';
          readonly name: 'baseStableRateOffset';
          readonly type: 'uint256';
        },
        {
          readonly internalType: 'uint256';
          readonly name: 'stableRateExcessOffset';
          readonly type: 'uint256';
        },
        {
          readonly internalType: 'uint256';
          readonly name: 'optimalStableToTotalDebtRatio';
          readonly type: 'uint256';
        },
      ];
      readonly stateMutability: 'nonpayable';
      readonly type: 'constructor';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'ADDRESSES_PROVIDER';
      readonly outputs: readonly [
        {
          readonly internalType: 'contract IPoolAddressesProvider';
          readonly name: '';
          readonly type: 'address';
        },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'MAX_EXCESS_STABLE_TO_TOTAL_DEBT_RATIO';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'MAX_EXCESS_USAGE_RATIO';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'OPTIMAL_STABLE_TO_TOTAL_DEBT_RATIO';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'OPTIMAL_USAGE_RATIO';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [
        {
          readonly components: readonly [
            {
              readonly internalType: 'uint256';
              readonly name: 'unbacked';
              readonly type: 'uint256';
            },
            {
              readonly internalType: 'uint256';
              readonly name: 'liquidityAdded';
              readonly type: 'uint256';
            },
            {
              readonly internalType: 'uint256';
              readonly name: 'liquidityTaken';
              readonly type: 'uint256';
            },
            {
              readonly internalType: 'uint256';
              readonly name: 'totalStableDebt';
              readonly type: 'uint256';
            },
            {
              readonly internalType: 'uint256';
              readonly name: 'totalVariableDebt';
              readonly type: 'uint256';
            },
            {
              readonly internalType: 'uint256';
              readonly name: 'averageStableBorrowRate';
              readonly type: 'uint256';
            },
            {
              readonly internalType: 'uint256';
              readonly name: 'reserveFactor';
              readonly type: 'uint256';
            },
            {
              readonly internalType: 'address';
              readonly name: 'reserve';
              readonly type: 'address';
            },
            { readonly internalType: 'address'; readonly name: 'aToken'; readonly type: 'address' },
          ];
          readonly internalType: 'struct DataTypes.CalculateInterestRatesParams';
          readonly name: 'params';
          readonly type: 'tuple';
        },
      ];
      readonly name: 'calculateInterestRates';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'getBaseStableBorrowRate';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'getBaseVariableBorrowRate';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'getMaxVariableBorrowRate';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'getStableRateExcessOffset';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'getStableRateSlope1';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'getStableRateSlope2';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'getVariableRateSlope1';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'getVariableRateSlope2';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
  ] satisfies Abi;
