// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import dustLockLegendaryLedgerAbiJson from './dustLockLegendaryLedgerAbi.json';

export const dustLockLegendaryLedgerAbi = dustLockLegendaryLedgerAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      { readonly name: 'dustLock_'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: 'initialOwner_';
        readonly type: 'address';
        readonly internalType: 'address';
      },
      { readonly name: 'threshold_'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'acceptOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'createLock';
    readonly inputs: readonly [
      { readonly name: 'value'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'lockDuration'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: 'tokenId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'createLockPermanent';
    readonly inputs: readonly [
      { readonly name: 'value'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'lockDuration'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: 'tokenId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'dustLock';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IDustLock' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'dustToken';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IERC20' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'hasLegendaryAttempt';
    readonly inputs: readonly [
      { readonly name: 'tokenId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'legendaryAttemptThreshold';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'threshold'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'legendaryAttemptTypeOf';
    readonly inputs: readonly [
      { readonly name: 'tokenId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: 'attemptType'; readonly type: 'uint8'; readonly internalType: 'uint8' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'owner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'pendingOwner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'recoverERC20';
    readonly inputs: readonly [
      { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'recipient'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'recoverNative';
    readonly inputs: readonly [
      { readonly name: 'recipient'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'renounceOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'setLegendaryAttemptThreshold';
    readonly inputs: readonly [
      { readonly name: 'threshold'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'transferOwnership';
    readonly inputs: readonly [
      { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'event';
    readonly name: 'ERC20Recovered';
    readonly inputs: readonly [
      {
        readonly name: 'token';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'recipient';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'amount';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'LegendaryAttemptThresholdUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'threshold';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'LegendaryLedgerAttemptRecorded';
    readonly inputs: readonly [
      {
        readonly name: 'owner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'tokenId';
        readonly type: 'uint256';
        readonly indexed: true;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'attemptType';
        readonly type: 'uint8';
        readonly indexed: true;
        readonly internalType: 'uint8';
      },
      {
        readonly name: 'value';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'lockDuration';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'NativeRecovered';
    readonly inputs: readonly [
      {
        readonly name: 'recipient';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'amount';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferStarted';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferred';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'InsufficientNativeRecoveryBalance';
    readonly inputs: readonly [
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'balance'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidERC20RecoveryAmount';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidERC20RecoveryRecipient';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidERC20RecoveryToken';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidLegendaryAttemptThreshold';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidNativeRecoveryAmount';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidNativeRecoveryRecipient';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'LockAmountBelowDustLockMinimum';
    readonly inputs: readonly [
      { readonly name: 'value'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      {
        readonly name: 'minLockAmount';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'LockAmountBelowLegendaryThreshold';
    readonly inputs: readonly [
      { readonly name: 'value'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'threshold'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  { readonly type: 'error'; readonly name: 'NativeRecoveryFailed'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'RenounceOwnershipDisabled';
    readonly inputs: readonly [];
  },
] satisfies Abi;
