// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import erc20AbiJson from './erc20Abi.json';

export const erc20Abi = erc20AbiJson as unknown as readonly [
  {
    readonly inputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'constructor';
  },
  { readonly inputs: readonly []; readonly name: 'AddressZero'; readonly type: 'error' },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: false;
        readonly internalType: 'address';
        readonly name: 'previousAdmin';
        readonly type: 'address';
      },
      {
        readonly indexed: false;
        readonly internalType: 'address';
        readonly name: 'newAdmin';
        readonly type: 'address';
      },
    ];
    readonly name: 'AdminChanged';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'owner';
        readonly type: 'address';
      },
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'spender';
        readonly type: 'address';
      },
      {
        readonly indexed: false;
        readonly internalType: 'uint256';
        readonly name: 'value';
        readonly type: 'uint256';
      },
    ];
    readonly name: 'Approval';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'beacon';
        readonly type: 'address';
      },
    ];
    readonly name: 'BeaconUpgraded';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [];
    readonly name: 'EIP712DomainChanged';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: false;
        readonly internalType: 'uint8';
        readonly name: 'version';
        readonly type: 'uint8';
      },
    ];
    readonly name: 'Initialized';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'previousOwner';
        readonly type: 'address';
      },
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'newOwner';
        readonly type: 'address';
      },
    ];
    readonly name: 'OwnershipTransferStarted';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'previousOwner';
        readonly type: 'address';
      },
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'newOwner';
        readonly type: 'address';
      },
    ];
    readonly name: 'OwnershipTransferred';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: false;
        readonly internalType: 'address';
        readonly name: 'account';
        readonly type: 'address';
      },
    ];
    readonly name: 'Paused';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'from';
        readonly type: 'address';
      },
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'to';
        readonly type: 'address';
      },
      {
        readonly indexed: false;
        readonly internalType: 'uint256';
        readonly name: 'value';
        readonly type: 'uint256';
      },
    ];
    readonly name: 'Transfer';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: false;
        readonly internalType: 'address';
        readonly name: 'account';
        readonly type: 'address';
      },
    ];
    readonly name: 'Unpaused';
    readonly type: 'event';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'implementation';
        readonly type: 'address';
      },
    ];
    readonly name: 'Upgraded';
    readonly type: 'event';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'DOMAIN_SEPARATOR';
    readonly outputs: readonly [
      { readonly internalType: 'bytes32'; readonly name: ''; readonly type: 'bytes32' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'acceptOwnership';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'owner'; readonly type: 'address' },
      { readonly internalType: 'address'; readonly name: 'spender'; readonly type: 'address' },
    ];
    readonly name: 'allowance';
    readonly outputs: readonly [
      { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'spender'; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'amount'; readonly type: 'uint256' },
    ];
    readonly name: 'approve';
    readonly outputs: readonly [
      { readonly internalType: 'bool'; readonly name: ''; readonly type: 'bool' },
    ];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'account'; readonly type: 'address' },
    ];
    readonly name: 'balanceOf';
    readonly outputs: readonly [
      { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'decimals';
    readonly outputs: readonly [
      { readonly internalType: 'uint8'; readonly name: ''; readonly type: 'uint8' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'spender'; readonly type: 'address' },
      {
        readonly internalType: 'uint256';
        readonly name: 'subtractedValue';
        readonly type: 'uint256';
      },
    ];
    readonly name: 'decreaseAllowance';
    readonly outputs: readonly [
      { readonly internalType: 'bool'; readonly name: ''; readonly type: 'bool' },
    ];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'eip712Domain';
    readonly outputs: readonly [
      { readonly internalType: 'bytes1'; readonly name: 'fields'; readonly type: 'bytes1' },
      { readonly internalType: 'string'; readonly name: 'name'; readonly type: 'string' },
      { readonly internalType: 'string'; readonly name: 'version'; readonly type: 'string' },
      { readonly internalType: 'uint256'; readonly name: 'chainId'; readonly type: 'uint256' },
      {
        readonly internalType: 'address';
        readonly name: 'verifyingContract';
        readonly type: 'address';
      },
      { readonly internalType: 'bytes32'; readonly name: 'salt'; readonly type: 'bytes32' },
      {
        readonly internalType: 'uint256[]';
        readonly name: 'extensions';
        readonly type: 'uint256[]';
      },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'spender'; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'addedValue'; readonly type: 'uint256' },
    ];
    readonly name: 'increaseAllowance';
    readonly outputs: readonly [
      { readonly internalType: 'bool'; readonly name: ''; readonly type: 'bool' },
    ];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'initialOwner'; readonly type: 'address' },
    ];
    readonly name: 'initialize';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'name';
    readonly outputs: readonly [
      { readonly internalType: 'string'; readonly name: ''; readonly type: 'string' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'owner'; readonly type: 'address' },
    ];
    readonly name: 'nonces';
    readonly outputs: readonly [
      { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'owner';
    readonly outputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'pause';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'paused';
    readonly outputs: readonly [
      { readonly internalType: 'bool'; readonly name: ''; readonly type: 'bool' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'pendingOwner';
    readonly outputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'owner'; readonly type: 'address' },
      { readonly internalType: 'address'; readonly name: 'spender'; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'value'; readonly type: 'uint256' },
      { readonly internalType: 'uint256'; readonly name: 'deadline'; readonly type: 'uint256' },
      { readonly internalType: 'uint8'; readonly name: 'v'; readonly type: 'uint8' },
      { readonly internalType: 'bytes32'; readonly name: 'r'; readonly type: 'bytes32' },
      { readonly internalType: 'bytes32'; readonly name: 's'; readonly type: 'bytes32' },
    ];
    readonly name: 'permit';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'proxiableUUID';
    readonly outputs: readonly [
      { readonly internalType: 'bytes32'; readonly name: ''; readonly type: 'bytes32' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'renounceOwnership';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'symbol';
    readonly outputs: readonly [
      { readonly internalType: 'string'; readonly name: ''; readonly type: 'string' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'totalSupply';
    readonly outputs: readonly [
      { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'to'; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'amount'; readonly type: 'uint256' },
    ];
    readonly name: 'transfer';
    readonly outputs: readonly [
      { readonly internalType: 'bool'; readonly name: ''; readonly type: 'bool' },
    ];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'from'; readonly type: 'address' },
      { readonly internalType: 'address'; readonly name: 'to'; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'amount'; readonly type: 'uint256' },
    ];
    readonly name: 'transferFrom';
    readonly outputs: readonly [
      { readonly internalType: 'bool'; readonly name: ''; readonly type: 'bool' },
    ];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'newOwner'; readonly type: 'address' },
    ];
    readonly name: 'transferOwnership';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'unpause';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: 'address';
        readonly name: 'newImplementation';
        readonly type: 'address';
      },
    ];
    readonly name: 'upgradeTo';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      {
        readonly internalType: 'address';
        readonly name: 'newImplementation';
        readonly type: 'address';
      },
      { readonly internalType: 'bytes'; readonly name: 'data'; readonly type: 'bytes' },
    ];
    readonly name: 'upgradeToAndCall';
    readonly outputs: readonly [];
    readonly stateMutability: 'payable';
    readonly type: 'function';
  },
] satisfies Abi;
