// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import governedPriceOracleAbiJson from './governedPriceOracleAbi.json';

export const governedPriceOracleAbi = governedPriceOracleAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      { readonly name: 'answer'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: '_description'; readonly type: 'string'; readonly internalType: 'string' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'acceptOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'decimals';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint8'; readonly internalType: 'uint8' },
    ];
    readonly stateMutability: 'pure';
  },
  {
    readonly type: 'function';
    readonly name: 'description';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'string'; readonly internalType: 'string' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getAnswer';
    readonly inputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'int256'; readonly internalType: 'int256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getRoundData';
    readonly inputs: readonly [
      {
        readonly name: 'requestedRoundId';
        readonly type: 'uint80';
        readonly internalType: 'uint80';
      },
    ];
    readonly outputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint80'; readonly internalType: 'uint80' },
      { readonly name: 'answer'; readonly type: 'int256'; readonly internalType: 'int256' },
      { readonly name: 'startedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      {
        readonly name: 'answeredInRound';
        readonly type: 'uint80';
        readonly internalType: 'uint80';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getTimestamp';
    readonly inputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestAnswer';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'int256'; readonly internalType: 'int256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestRound';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestRoundData';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint80'; readonly internalType: 'uint80' },
      { readonly name: 'answer'; readonly type: 'int256'; readonly internalType: 'int256' },
      { readonly name: 'startedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      {
        readonly name: 'answeredInRound';
        readonly type: 'uint80';
        readonly internalType: 'uint80';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestTimestamp';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'owner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'pendingOwner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'renounceOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'setPrice';
    readonly inputs: readonly [
      { readonly name: 'newAnswer'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'transferOwnership';
    readonly inputs: readonly [
      { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'version';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'pure';
  },
  {
    readonly type: 'event';
    readonly name: 'AnswerUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'current';
        readonly type: 'int256';
        readonly indexed: true;
        readonly internalType: 'int256';
      },
      {
        readonly name: 'roundId';
        readonly type: 'uint256';
        readonly indexed: true;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'updatedAt';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'NewRound';
    readonly inputs: readonly [
      {
        readonly name: 'roundId';
        readonly type: 'uint256';
        readonly indexed: true;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'startedBy';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'startedAt';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferStarted';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferred';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'PriceUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'previousAnswer';
        readonly type: 'int256';
        readonly indexed: false;
        readonly internalType: 'int256';
      },
      {
        readonly name: 'newAnswer';
        readonly type: 'int256';
        readonly indexed: false;
        readonly internalType: 'int256';
      },
    ];
    readonly anonymous: false;
  },
  { readonly type: 'error'; readonly name: 'InvalidPrice'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'OwnershipRequired'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'StaleRound'; readonly inputs: readonly [] },
] satisfies Abi;
