// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import leaderboardKeeperAbiJson from './leaderboardKeeperAbi.json';

export const leaderboardKeeperAbi = leaderboardKeeperAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      { readonly name: '_dustLock'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: '_nftRegistry'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_BATCH_SIZE';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'dustLock';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract ILeaderboardKeeperDustLock';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'emergencySettle';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'initialize';
    readonly inputs: readonly [
      { readonly name: 'initialOwner'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: 'initialKeeper';
        readonly type: 'address';
        readonly internalType: 'address';
      },
      {
        readonly name: 'initialInterval';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'keeper';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'lastSettlement';
    readonly inputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'minSettlementInterval';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'nftRegistry';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract ILeaderboardKeeperNFTRegistry';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'owner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'renounceOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'selfSyncCooldown';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'setKeeper';
    readonly inputs: readonly [
      { readonly name: 'newKeeper'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'setMinSettlementInterval';
    readonly inputs: readonly [
      { readonly name: 'newInterval'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'setSelfSyncCooldown';
    readonly inputs: readonly [
      { readonly name: 'newCooldown'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'settle';
    readonly inputs: readonly [
      { readonly name: 'users'; readonly type: 'address[]'; readonly internalType: 'address[]' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'syncLPPositions';
    readonly inputs: readonly [
      { readonly name: 'users'; readonly type: 'address[]'; readonly internalType: 'address[]' },
      { readonly name: 'pools'; readonly type: 'address[]'; readonly internalType: 'address[]' },
      { readonly name: 'tokenIds'; readonly type: 'uint256[]'; readonly internalType: 'uint256[]' },
      { readonly name: 'tickLowers'; readonly type: 'int24[]'; readonly internalType: 'int24[]' },
      { readonly name: 'tickUppers'; readonly type: 'int24[]'; readonly internalType: 'int24[]' },
      {
        readonly name: 'liquidities';
        readonly type: 'uint128[]';
        readonly internalType: 'uint128[]';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'syncMyState';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'syncNFTBalances';
    readonly inputs: readonly [
      { readonly name: 'users'; readonly type: 'address[]'; readonly internalType: 'address[]' },
      {
        readonly name: 'collections';
        readonly type: 'address[]';
        readonly internalType: 'address[]';
      },
      { readonly name: 'balances'; readonly type: 'uint256[]'; readonly internalType: 'uint256[]' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'syncVotingPower';
    readonly inputs: readonly [
      { readonly name: 'users'; readonly type: 'address[]'; readonly internalType: 'address[]' },
      {
        readonly name: 'votingPowers';
        readonly type: 'uint256[]';
        readonly internalType: 'uint256[]';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'transferOwnership';
    readonly inputs: readonly [
      { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'event';
    readonly name: 'BatchComplete';
    readonly inputs: readonly [
      {
        readonly name: 'operation';
        readonly type: 'string';
        readonly indexed: false;
        readonly internalType: 'string';
      },
      {
        readonly name: 'count';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'timestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'Initialized';
    readonly inputs: readonly [
      {
        readonly name: 'version';
        readonly type: 'uint8';
        readonly indexed: false;
        readonly internalType: 'uint8';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'KeeperUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'oldKeeper';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newKeeper';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'LPPositionSynced';
    readonly inputs: readonly [
      {
        readonly name: 'user';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'pool';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'tokenId';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'tickLower';
        readonly type: 'int24';
        readonly indexed: false;
        readonly internalType: 'int24';
      },
      {
        readonly name: 'tickUpper';
        readonly type: 'int24';
        readonly indexed: false;
        readonly internalType: 'int24';
      },
      {
        readonly name: 'liquidity';
        readonly type: 'uint128';
        readonly indexed: false;
        readonly internalType: 'uint128';
      },
      {
        readonly name: 'timestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'MinSettlementIntervalUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'oldInterval';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newInterval';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'NFTBalanceSynced';
    readonly inputs: readonly [
      {
        readonly name: 'user';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'collection';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'balance';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'timestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferred';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'SelfSyncCooldownUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'oldCooldown';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newCooldown';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'UserSettled';
    readonly inputs: readonly [
      {
        readonly name: 'user';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'timestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'VotingPowerSynced';
    readonly inputs: readonly [
      {
        readonly name: 'user';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'votingPower';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'timestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'ArrayLengthMismatch';
    readonly inputs: readonly [
      { readonly name: 'expected'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'actual'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'BatchTooLarge';
    readonly inputs: readonly [
      { readonly name: 'batchSize'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'maxBatchSize'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'CooldownNotElapsed';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: 'timeSinceLast';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      { readonly name: 'minInterval'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'NotKeeper';
    readonly inputs: readonly [
      { readonly name: 'caller'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
] satisfies Abi;
