// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import marketHoursPriceAdapterAbiJson from './marketHoursPriceAdapterAbi.json';

export const marketHoursPriceAdapterAbi = marketHoursPriceAdapterAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      {
        readonly name: 'feed';
        readonly type: 'address';
        readonly internalType: 'contract AggregatorV3Interface';
      },
      {
        readonly name: 'calendar';
        readonly type: 'address';
        readonly internalType: 'contract ISessionCalendar';
      },
      {
        readonly name: 'maxSessionAge';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'maxClosureAge';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      { readonly name: '_description'; readonly type: 'string'; readonly internalType: 'string' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'CALENDAR';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract ISessionCalendar';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'FEED';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract AggregatorV3Interface';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_CLOSURE_AGE';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_CLOSURE_AGE_CEILING';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_SESSION_AGE';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_SESSION_AGE_CEILING';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'decimals';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint8'; readonly internalType: 'uint8' },
    ];
    readonly stateMutability: 'pure';
  },
  {
    readonly type: 'function';
    readonly name: 'description';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'string'; readonly internalType: 'string' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestAnswer';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'int256'; readonly internalType: 'int256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestRoundData';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint80'; readonly internalType: 'uint80' },
      { readonly name: 'answer'; readonly type: 'int256'; readonly internalType: 'int256' },
      { readonly name: 'startedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      {
        readonly name: 'answeredInRound';
        readonly type: 'uint80';
        readonly internalType: 'uint80';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestTimestamp';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'version';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'pure';
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'InvalidCalendar'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'InvalidClosureAge'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'InvalidDecimals'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'InvalidFeed'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'InvalidSessionAge'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'ZeroAmount'; readonly inputs: readonly [] },
] satisfies Abi;
