// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import neverlandPendleMaturityGatewayAbiJson from './neverlandPendleMaturityGatewayAbi.json';

export const neverlandPendleMaturityGatewayAbi =
  neverlandPendleMaturityGatewayAbiJson as unknown as readonly [
    {
      readonly type: 'constructor';
      readonly inputs: readonly [
        {
          readonly name: 'pool_';
          readonly type: 'address';
          readonly internalType: 'contract IPool';
        },
        { readonly name: 'debtAsset_'; readonly type: 'address'; readonly internalType: 'address' },
        { readonly name: 'morpho_'; readonly type: 'address'; readonly internalType: 'address' },
        {
          readonly name: 'flashPool_';
          readonly type: 'address';
          readonly internalType: 'contract IPool';
        },
        {
          readonly name: 'pendleRouter_';
          readonly type: 'address';
          readonly internalType: 'address';
        },
        {
          readonly name: 'initialMarket_';
          readonly type: 'address';
          readonly internalType: 'address';
        },
        {
          readonly name: 'initialOwner_';
          readonly type: 'address';
          readonly internalType: 'address';
        },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'ADDRESSES_PROVIDER';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'address';
          readonly internalType: 'contract IPoolAddressesProvider';
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'DEBT_ASSET';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'FLASH_POOL';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IPool' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'MAX_ORACLE_DEVIATION_BPS';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'MORPHO';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'PENDLE_ROUTER';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'POOL';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IPool' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'acceptOwnership';
      readonly inputs: readonly [];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'close';
      readonly inputs: readonly [
        {
          readonly name: 'params';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.CloseParams';
          readonly components: readonly [
            { readonly name: 'ptOld'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minSurplusOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'maxRounds';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
          ];
        },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.CloseResult';
          readonly components: readonly [
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'debt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'debtRepaid';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'debtAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'surplus';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'flashSource';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'flashCash';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'healthFactorAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAvailable';
              readonly type: 'bool';
              readonly internalType: 'bool';
            },
          ];
        },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'closeWithPermit';
      readonly inputs: readonly [
        {
          readonly name: 'params';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.CloseParams';
          readonly components: readonly [
            { readonly name: 'ptOld'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minSurplusOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'maxRounds';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
          ];
        },
        {
          readonly name: 'permit';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.PermitParams';
          readonly components: readonly [
            { readonly name: 'value'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'deadline';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'v'; readonly type: 'uint8'; readonly internalType: 'uint8' },
            { readonly name: 'r'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
            { readonly name: 's'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
          ];
        },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.CloseResult';
          readonly components: readonly [
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'debt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'debtRepaid';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'debtAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'surplus';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'flashSource';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'flashCash';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'healthFactorAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAvailable';
              readonly type: 'bool';
              readonly internalType: 'bool';
            },
          ];
        },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'emergencyTokenTransfer';
      readonly inputs: readonly [
        { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
        { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
        { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'executeOperation';
      readonly inputs: readonly [
        { readonly name: 'assets'; readonly type: 'address[]'; readonly internalType: 'address[]' },
        {
          readonly name: 'amounts';
          readonly type: 'uint256[]';
          readonly internalType: 'uint256[]';
        },
        {
          readonly name: 'premiums';
          readonly type: 'uint256[]';
          readonly internalType: 'uint256[]';
        },
        { readonly name: 'initiator'; readonly type: 'address'; readonly internalType: 'address' },
        { readonly name: 'params'; readonly type: 'bytes'; readonly internalType: 'bytes' },
      ];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'bool'; readonly internalType: 'bool' },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'flashCapacity';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: 'source'; readonly type: 'address'; readonly internalType: 'address' },
        { readonly name: 'cash'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'flashPoolCapacity';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'migrate';
      readonly inputs: readonly [
        {
          readonly name: 'params';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.MigrateParams';
          readonly components: readonly [
            { readonly name: 'ptOld'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'ptNew'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'repayAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minPtOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minHealthFactor';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'maxRounds';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
          ];
        },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.MigrateResult';
          readonly components: readonly [
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'debt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'repay'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'spent'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'ptOut'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'debtAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'surplus';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'flashSource';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'flashCash';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'oracleMinimumPtOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAvailable';
              readonly type: 'bool';
              readonly internalType: 'bool';
            },
          ];
        },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'migrateWithPermit';
      readonly inputs: readonly [
        {
          readonly name: 'params';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.MigrateParams';
          readonly components: readonly [
            { readonly name: 'ptOld'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'ptNew'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'repayAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minPtOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minHealthFactor';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'maxRounds';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
          ];
        },
        {
          readonly name: 'permit';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.PermitParams';
          readonly components: readonly [
            { readonly name: 'value'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'deadline';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'v'; readonly type: 'uint8'; readonly internalType: 'uint8' },
            { readonly name: 'r'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
            { readonly name: 's'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
          ];
        },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.MigrateResult';
          readonly components: readonly [
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'debt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'repay'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'spent'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'ptOut'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'debtAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'surplus';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'flashSource';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'flashCash';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'oracleMinimumPtOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAvailable';
              readonly type: 'bool';
              readonly internalType: 'bool';
            },
          ];
        },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'migrationMarket';
      readonly inputs: readonly [
        { readonly name: 'pt'; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly outputs: readonly [
        { readonly name: 'market'; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'migrationTargets';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        {
          readonly name: 'targets';
          readonly type: 'tuple[]';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.MigrationTarget[]';
          readonly components: readonly [
            { readonly name: 'pt'; readonly type: 'address'; readonly internalType: 'address' },
            { readonly name: 'market'; readonly type: 'address'; readonly internalType: 'address' },
          ];
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'onMorphoFlashLoan';
      readonly inputs: readonly [
        { readonly name: 'assets'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'data'; readonly type: 'bytes'; readonly internalType: 'bytes' },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'owner';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'pendingOwner';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'previewClose';
      readonly inputs: readonly [
        {
          readonly name: 'params';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.CloseParams';
          readonly components: readonly [
            { readonly name: 'ptOld'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minSurplusOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'maxRounds';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
          ];
        },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.CloseResult';
          readonly components: readonly [
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'debt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'debtRepaid';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'debtAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'surplus';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'flashSource';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'flashCash';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'healthFactorAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAvailable';
              readonly type: 'bool';
              readonly internalType: 'bool';
            },
          ];
        },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'previewCloseWithPermit';
      readonly inputs: readonly [
        {
          readonly name: 'params';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.CloseParams';
          readonly components: readonly [
            { readonly name: 'ptOld'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minSurplusOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'maxRounds';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
          ];
        },
        {
          readonly name: 'permit';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.PermitParams';
          readonly components: readonly [
            { readonly name: 'value'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'deadline';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'v'; readonly type: 'uint8'; readonly internalType: 'uint8' },
            { readonly name: 'r'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
            { readonly name: 's'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
          ];
        },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.CloseResult';
          readonly components: readonly [
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'debt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'debtRepaid';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'debtAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'surplus';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'flashSource';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'flashCash';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'healthFactorAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAvailable';
              readonly type: 'bool';
              readonly internalType: 'bool';
            },
          ];
        },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'previewMigrate';
      readonly inputs: readonly [
        {
          readonly name: 'params';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.MigrateParams';
          readonly components: readonly [
            { readonly name: 'ptOld'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'ptNew'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'repayAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minPtOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minHealthFactor';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'maxRounds';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
          ];
        },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.MigrateResult';
          readonly components: readonly [
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'debt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'repay'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'spent'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'ptOut'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'debtAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'surplus';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'flashSource';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'flashCash';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'oracleMinimumPtOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAvailable';
              readonly type: 'bool';
              readonly internalType: 'bool';
            },
          ];
        },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'previewMigrateWithPermit';
      readonly inputs: readonly [
        {
          readonly name: 'params';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.MigrateParams';
          readonly components: readonly [
            { readonly name: 'ptOld'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'ptNew'; readonly type: 'address'; readonly internalType: 'address' },
            {
              readonly name: 'repayAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minPtOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'minHealthFactor';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'maxRounds';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
          ];
        },
        {
          readonly name: 'permit';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.PermitParams';
          readonly components: readonly [
            { readonly name: 'value'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'deadline';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'v'; readonly type: 'uint8'; readonly internalType: 'uint8' },
            { readonly name: 'r'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
            { readonly name: 's'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
          ];
        },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple';
          readonly internalType: 'struct INeverlandPendleMaturityGateway.MigrateResult';
          readonly components: readonly [
            {
              readonly name: 'ptAmount';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'debt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'repay'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'spent'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            { readonly name: 'ptOut'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'debtAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'surplus';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'flashSource';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'flashCash';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
            {
              readonly name: 'oracleMinimumPtOut';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAfter';
              readonly type: 'uint256';
              readonly internalType: 'uint256';
            },
            {
              readonly name: 'healthFactorAvailable';
              readonly type: 'bool';
              readonly internalType: 'bool';
            },
          ];
        },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'removeMigrationTarget';
      readonly inputs: readonly [
        { readonly name: 'pt'; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'renounceOwnership';
      readonly inputs: readonly [];
      readonly outputs: readonly [];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'setMigrationTarget';
      readonly inputs: readonly [
        { readonly name: 'market'; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'simulate';
      readonly inputs: readonly [
        { readonly name: 'callData'; readonly type: 'bytes'; readonly internalType: 'bytes' },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'transferOwnership';
      readonly inputs: readonly [
        { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'event';
      readonly name: 'ERC20Recovered';
      readonly inputs: readonly [
        {
          readonly name: 'token';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'to';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'amount';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'MigrationTargetRemoved';
      readonly inputs: readonly [
        {
          readonly name: 'pt';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'market';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'MigrationTargetSet';
      readonly inputs: readonly [
        {
          readonly name: 'pt';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'market';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'OwnershipTransferStarted';
      readonly inputs: readonly [
        {
          readonly name: 'previousOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'newOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'OwnershipTransferred';
      readonly inputs: readonly [
        {
          readonly name: 'previousOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'newOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'PositionClosed';
      readonly inputs: readonly [
        {
          readonly name: 'user';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'ptOld';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'ptRedeemed';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'debtRepaid';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'surplus';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'to';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'rounds';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'PositionMigrated';
      readonly inputs: readonly [
        {
          readonly name: 'user';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'ptOld';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'ptNew';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'ptOldAmount';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'ptNewAmount';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'debtRepaid';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'rounds';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
    {
      readonly type: 'error';
      readonly name: 'BalanceMismatch';
      readonly inputs: readonly [
        { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
        { readonly name: 'expected'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'actual'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'CollateralNotEnabled';
      readonly inputs: readonly [
        { readonly name: 'pt'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'FlashCallbackUnauthorized';
      readonly inputs: readonly [];
    },
    {
      readonly type: 'error';
      readonly name: 'HealthFactorBelowMinimum';
      readonly inputs: readonly [
        {
          readonly name: 'healthFactor';
          readonly type: 'uint256';
          readonly internalType: 'uint256';
        },
        { readonly name: 'minimum'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'InsufficientFlashLiquidity';
      readonly inputs: readonly [
        { readonly name: 'required'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'perRound'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'maxRounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
    },
    { readonly type: 'error'; readonly name: 'InvalidAmount'; readonly inputs: readonly [] },
    {
      readonly type: 'error';
      readonly name: 'InvalidMarket';
      readonly inputs: readonly [
        { readonly name: 'market'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'InvalidOraclePrice';
      readonly inputs: readonly [
        { readonly name: 'asset'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'InvalidSimulationCall';
      readonly inputs: readonly [];
    },
    { readonly type: 'error'; readonly name: 'InvalidToAddress'; readonly inputs: readonly [] },
    {
      readonly type: 'error';
      readonly name: 'MigrationTargetNotEnabled';
      readonly inputs: readonly [
        { readonly name: 'pt'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'NotPrincipalToken';
      readonly inputs: readonly [
        { readonly name: 'asset'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'OutputBelowMinimum';
      readonly inputs: readonly [
        { readonly name: 'output'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'minimum'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'OwnableInvalidOwner';
      readonly inputs: readonly [
        { readonly name: 'owner'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'OwnableUnauthorizedAccount';
      readonly inputs: readonly [
        { readonly name: 'account'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    { readonly type: 'error'; readonly name: 'OwnershipRequired'; readonly inputs: readonly [] },
    {
      readonly type: 'error';
      readonly name: 'PrincipalTokenNotMatured';
      readonly inputs: readonly [
        { readonly name: 'pt'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'RedemptionShortfall';
      readonly inputs: readonly [
        { readonly name: 'expected'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'received'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'ReentrancyGuardReentrantCall';
      readonly inputs: readonly [];
    },
    {
      readonly type: 'error';
      readonly name: 'ReserveIndexNotPar';
      readonly inputs: readonly [
        { readonly name: 'pt'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'ReserveNotListed';
      readonly inputs: readonly [
        { readonly name: 'asset'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'SafeERC20FailedOperation';
      readonly inputs: readonly [
        { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    { readonly type: 'error'; readonly name: 'SameAddress'; readonly inputs: readonly [] },
    {
      readonly type: 'error';
      readonly name: 'TargetMarketExpired';
      readonly inputs: readonly [
        { readonly name: 'market'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
    {
      readonly type: 'error';
      readonly name: 'UnsupportedSy';
      readonly inputs: readonly [
        { readonly name: 'sy'; readonly type: 'address'; readonly internalType: 'address' },
      ];
    },
  ] satisfies Abi;
