// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import neverlandNativeGatewayAbiJson from './neverlandNativeGatewayAbi.json';

export const neverlandNativeGatewayAbi = neverlandNativeGatewayAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      {
        readonly name: 'wrappedNative_';
        readonly type: 'address';
        readonly internalType: 'contract IWETH';
      },
      { readonly name: 'pool_'; readonly type: 'address'; readonly internalType: 'contract IPool' },
      {
        readonly name: 'initialOwner_';
        readonly type: 'address';
        readonly internalType: 'address';
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  { readonly type: 'fallback'; readonly stateMutability: 'payable' },
  { readonly type: 'receive'; readonly stateMutability: 'payable' },
  {
    readonly type: 'function';
    readonly name: 'POOL';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IPool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'WRAPPED_NATIVE';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IWETH' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'acceptOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'borrow';
    readonly inputs: readonly [
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      {
        readonly name: 'interestRateMode';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      { readonly name: 'referralCode'; readonly type: 'uint16'; readonly internalType: 'uint16' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'emergencyNativeTransfer';
    readonly inputs: readonly [
      { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'emergencyTokenTransfer';
    readonly inputs: readonly [
      { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'owner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'pendingOwner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'renounceOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'repay';
    readonly inputs: readonly [
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'rateMode'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'onBehalfOf'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'payable';
  },
  {
    readonly type: 'function';
    readonly name: 'supply';
    readonly inputs: readonly [
      { readonly name: 'onBehalfOf'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'referralCode'; readonly type: 'uint16'; readonly internalType: 'uint16' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'payable';
  },
  {
    readonly type: 'function';
    readonly name: 'transferOwnership';
    readonly inputs: readonly [
      { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'withdraw';
    readonly inputs: readonly [
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'withdrawWithPermit';
    readonly inputs: readonly [
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'deadline'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'permitV'; readonly type: 'uint8'; readonly internalType: 'uint8' },
      { readonly name: 'permitR'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
      { readonly name: 'permitS'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'event';
    readonly name: 'ERC20Recovered';
    readonly inputs: readonly [
      {
        readonly name: 'token';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'to';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'amount';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'NativeRecovered';
    readonly inputs: readonly [
      {
        readonly name: 'to';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'amount';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferStarted';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferred';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'DirectNativeTransferNotAllowed';
    readonly inputs: readonly [
      { readonly name: 'sender'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  { readonly type: 'error'; readonly name: 'FallbackNotAllowed'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'InsufficientRepaymentValue';
    readonly inputs: readonly [
      { readonly name: 'provided'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'required'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  { readonly type: 'error'; readonly name: 'InvalidToAddress'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'InvalidUserAddress'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'NativeTransferFailed';
    readonly inputs: readonly [
      { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'OwnableInvalidOwner';
    readonly inputs: readonly [
      { readonly name: 'owner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'OwnableUnauthorizedAccount';
    readonly inputs: readonly [
      { readonly name: 'account'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  { readonly type: 'error'; readonly name: 'OwnershipRequired'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'ReentrancyGuardReentrantCall';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'SafeERC20FailedOperation';
    readonly inputs: readonly [
      { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
] satisfies Abi;
