// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import neverlandUiProviderAbiJson from './neverlandUiProviderAbi.json';

export const neverlandUiProviderAbi = neverlandUiProviderAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      { readonly name: '_dustLock'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: '_revenueReward';
        readonly type: 'address';
        readonly internalType: 'address';
      },
      {
        readonly name: '_dustRewardsController';
        readonly type: 'address';
        readonly internalType: 'address';
      },
      { readonly name: '_dustOracle'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: '_neverlandPoolRegistry';
        readonly type: 'address';
        readonly internalType: 'address';
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'DUST_HELPER';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract INeverlandDustHelper';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'DUST_LOCK';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IDustLock' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'DUST_REWARDS_CONTROLLER';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract IDustRewardsController';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'NEVERLAND_POOL_REGISTRY';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract IPoolAddressesProviderRegistry';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'REVENUE_REWARD';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract INeverlandUiRevenueReward';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getAllPrices';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: 'p';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandUiProvider.PriceData';
        readonly components: readonly [
          {
            readonly name: 'tokens';
            readonly type: 'address[]';
            readonly internalType: 'address[]';
          },
          {
            readonly name: 'prices';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'lastUpdated';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'resolvedMask';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'dustPriceFromOracle';
            readonly type: 'bool';
            readonly internalType: 'bool';
          },
          {
            readonly name: 'asOfBlock';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'asOfTimestamp';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getEssentialUserView';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'offset'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'limit'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandUiProvider.EssentialUserView';
        readonly components: readonly [
          {
            readonly name: 'user';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.UserDashboardData';
            readonly components: readonly [
              { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
              {
                readonly name: 'tokenIds';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'locks';
                readonly type: 'tuple[]';
                readonly internalType: 'struct INeverlandUiProvider.LockInfo[]';
                readonly components: readonly [
                  {
                    readonly name: 'tokenId';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'amount';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'end';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'effectiveStart';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'isPermanent';
                    readonly type: 'bool';
                    readonly internalType: 'bool';
                  },
                  {
                    readonly name: 'votingPower';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'rewardReceiver';
                    readonly type: 'address';
                    readonly internalType: 'address';
                  },
                  {
                    readonly name: 'owner';
                    readonly type: 'address';
                    readonly internalType: 'address';
                  },
                ];
              },
              {
                readonly name: 'rewardSummaries';
                readonly type: 'tuple[]';
                readonly internalType: 'struct INeverlandUiProvider.RewardSummary[]';
                readonly components: readonly [
                  {
                    readonly name: 'tokenId';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'revenueRewards';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'rewardTokens';
                    readonly type: 'address[]';
                    readonly internalType: 'address[]';
                  },
                ];
              },
              {
                readonly name: 'totalVotingPower';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'totalLockedAmount';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'rawTokenCount';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'nextRawOffset';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              { readonly name: 'hasMore'; readonly type: 'bool'; readonly internalType: 'bool' },
            ];
          },
          {
            readonly name: 'globalStats';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.GlobalStats';
            readonly components: readonly [
              {
                readonly name: 'totalSupply';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'totalVotingPower';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'permanentLockBalance';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'rewardTokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
              {
                readonly name: 'totalRewardsPerToken';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'epoch';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'activeTokenCount';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
            ];
          },
          {
            readonly name: 'emissions';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.EmissionData';
            readonly components: readonly [
              {
                readonly name: 'rewardTokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
              {
                readonly name: 'totalRewards';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              { readonly name: 'resolved'; readonly type: 'bool'; readonly internalType: 'bool' },
              {
                readonly name: 'asOfBlock';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'asOfTimestamp';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
            ];
          },
          {
            readonly name: 'marketData';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.MarketData';
            readonly components: readonly [
              {
                readonly name: 'rewardTokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
              {
                readonly name: 'rewardTokenBalances';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'distributionRates';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'nextEpochTimestamp';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'currentEpoch';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'epochRewards';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'nextEpochRewards';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'totalValueLockedUSD';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'followingEpochRewards';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'totalValueLockedUSDResolved';
                readonly type: 'bool';
                readonly internalType: 'bool';
              },
              {
                readonly name: 'asOfBlock';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'asOfTimestamp';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
            ];
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getGlobalStats';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandUiProvider.GlobalStats';
        readonly components: readonly [
          {
            readonly name: 'totalSupply';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'totalVotingPower';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'permanentLockBalance';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'rewardTokens';
            readonly type: 'address[]';
            readonly internalType: 'address[]';
          },
          {
            readonly name: 'totalRewardsPerToken';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          { readonly name: 'epoch'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'activeTokenCount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getMarketData';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: 'm';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandUiProvider.MarketData';
        readonly components: readonly [
          {
            readonly name: 'rewardTokens';
            readonly type: 'address[]';
            readonly internalType: 'address[]';
          },
          {
            readonly name: 'rewardTokenBalances';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'distributionRates';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'nextEpochTimestamp';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'currentEpoch';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'epochRewards';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'nextEpochRewards';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'totalValueLockedUSD';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'followingEpochRewards';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'totalValueLockedUSDResolved';
            readonly type: 'bool';
            readonly internalType: 'bool';
          },
          {
            readonly name: 'asOfBlock';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'asOfTimestamp';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getNetworkData';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandUiProvider.NetworkData';
        readonly components: readonly [
          {
            readonly name: 'currentBlock';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'currentTimestamp';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'gasPrice'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getProtocolMeta';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: 'meta';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandUiProvider.ProtocolMeta';
        readonly components: readonly [
          { readonly name: 'dustLock'; readonly type: 'address'; readonly internalType: 'address' },
          {
            readonly name: 'revenueReward';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'dustRewardsController';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'dustOracle';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'earlyWithdrawPenalty';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'minLockAmount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'rewardDistributor';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'revenueRewardTokens';
            readonly type: 'address[]';
            readonly internalType: 'address[]';
          },
          {
            readonly name: 'emissionRewardTokens';
            readonly type: 'address[]';
            readonly internalType: 'address[]';
          },
          {
            readonly name: 'emissionStrategies';
            readonly type: 'address[]';
            readonly internalType: 'address[]';
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getRegisteredPoolMarkets';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: 'markets';
        readonly type: 'tuple[]';
        readonly internalType: 'struct INeverlandUiProvider.PoolMarket[]';
        readonly components: readonly [
          { readonly name: 'provider'; readonly type: 'address'; readonly internalType: 'address' },
          { readonly name: 'marketId'; readonly type: 'string'; readonly internalType: 'string' },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getUiBootstrap';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: 'boot';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandUiProvider.UiBootstrap';
        readonly components: readonly [
          {
            readonly name: 'meta';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.ProtocolMeta';
            readonly components: readonly [
              {
                readonly name: 'dustLock';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'revenueReward';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'dustRewardsController';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'dustOracle';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'earlyWithdrawPenalty';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'minLockAmount';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'rewardDistributor';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'revenueRewardTokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
              {
                readonly name: 'emissionRewardTokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
              {
                readonly name: 'emissionStrategies';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
            ];
          },
          {
            readonly name: 'globalStats';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.GlobalStats';
            readonly components: readonly [
              {
                readonly name: 'totalSupply';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'totalVotingPower';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'permanentLockBalance';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'rewardTokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
              {
                readonly name: 'totalRewardsPerToken';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'epoch';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'activeTokenCount';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
            ];
          },
          {
            readonly name: 'marketData';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.MarketData';
            readonly components: readonly [
              {
                readonly name: 'rewardTokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
              {
                readonly name: 'rewardTokenBalances';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'distributionRates';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'nextEpochTimestamp';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'currentEpoch';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'epochRewards';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'nextEpochRewards';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'totalValueLockedUSD';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'followingEpochRewards';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'totalValueLockedUSDResolved';
                readonly type: 'bool';
                readonly internalType: 'bool';
              },
              {
                readonly name: 'asOfBlock';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'asOfTimestamp';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
            ];
          },
          {
            readonly name: 'allPrices';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.PriceData';
            readonly components: readonly [
              {
                readonly name: 'tokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
              {
                readonly name: 'prices';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'lastUpdated';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'resolvedMask';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'dustPriceFromOracle';
                readonly type: 'bool';
                readonly internalType: 'bool';
              },
              {
                readonly name: 'asOfBlock';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'asOfTimestamp';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
            ];
          },
          {
            readonly name: 'network';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.NetworkData';
            readonly components: readonly [
              {
                readonly name: 'currentBlock';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'currentTimestamp';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'gasPrice';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
            ];
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getUiFullBundle';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'offset'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'limit'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      {
        readonly name: 'bundle';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandUiProvider.UiFullBundle';
        readonly components: readonly [
          {
            readonly name: 'meta';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.ProtocolMeta';
            readonly components: readonly [
              {
                readonly name: 'dustLock';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'revenueReward';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'dustRewardsController';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'dustOracle';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'earlyWithdrawPenalty';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'minLockAmount';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'rewardDistributor';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'revenueRewardTokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
              {
                readonly name: 'emissionRewardTokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
              {
                readonly name: 'emissionStrategies';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
            ];
          },
          {
            readonly name: 'essential';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.EssentialUserView';
            readonly components: readonly [
              {
                readonly name: 'user';
                readonly type: 'tuple';
                readonly internalType: 'struct INeverlandUiProvider.UserDashboardData';
                readonly components: readonly [
                  {
                    readonly name: 'user';
                    readonly type: 'address';
                    readonly internalType: 'address';
                  },
                  {
                    readonly name: 'tokenIds';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'locks';
                    readonly type: 'tuple[]';
                    readonly internalType: 'struct INeverlandUiProvider.LockInfo[]';
                    readonly components: readonly [
                      {
                        readonly name: 'tokenId';
                        readonly type: 'uint256';
                        readonly internalType: 'uint256';
                      },
                      {
                        readonly name: 'amount';
                        readonly type: 'uint256';
                        readonly internalType: 'uint256';
                      },
                      {
                        readonly name: 'end';
                        readonly type: 'uint256';
                        readonly internalType: 'uint256';
                      },
                      {
                        readonly name: 'effectiveStart';
                        readonly type: 'uint256';
                        readonly internalType: 'uint256';
                      },
                      {
                        readonly name: 'isPermanent';
                        readonly type: 'bool';
                        readonly internalType: 'bool';
                      },
                      {
                        readonly name: 'votingPower';
                        readonly type: 'uint256';
                        readonly internalType: 'uint256';
                      },
                      {
                        readonly name: 'rewardReceiver';
                        readonly type: 'address';
                        readonly internalType: 'address';
                      },
                      {
                        readonly name: 'owner';
                        readonly type: 'address';
                        readonly internalType: 'address';
                      },
                    ];
                  },
                  {
                    readonly name: 'rewardSummaries';
                    readonly type: 'tuple[]';
                    readonly internalType: 'struct INeverlandUiProvider.RewardSummary[]';
                    readonly components: readonly [
                      {
                        readonly name: 'tokenId';
                        readonly type: 'uint256';
                        readonly internalType: 'uint256';
                      },
                      {
                        readonly name: 'revenueRewards';
                        readonly type: 'uint256[]';
                        readonly internalType: 'uint256[]';
                      },
                      {
                        readonly name: 'rewardTokens';
                        readonly type: 'address[]';
                        readonly internalType: 'address[]';
                      },
                    ];
                  },
                  {
                    readonly name: 'totalVotingPower';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'totalLockedAmount';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'rawTokenCount';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'nextRawOffset';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'hasMore';
                    readonly type: 'bool';
                    readonly internalType: 'bool';
                  },
                ];
              },
              {
                readonly name: 'globalStats';
                readonly type: 'tuple';
                readonly internalType: 'struct INeverlandUiProvider.GlobalStats';
                readonly components: readonly [
                  {
                    readonly name: 'totalSupply';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'totalVotingPower';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'permanentLockBalance';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'rewardTokens';
                    readonly type: 'address[]';
                    readonly internalType: 'address[]';
                  },
                  {
                    readonly name: 'totalRewardsPerToken';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'epoch';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'activeTokenCount';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                ];
              },
              {
                readonly name: 'emissions';
                readonly type: 'tuple';
                readonly internalType: 'struct INeverlandUiProvider.EmissionData';
                readonly components: readonly [
                  {
                    readonly name: 'rewardTokens';
                    readonly type: 'address[]';
                    readonly internalType: 'address[]';
                  },
                  {
                    readonly name: 'totalRewards';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'resolved';
                    readonly type: 'bool';
                    readonly internalType: 'bool';
                  },
                  {
                    readonly name: 'asOfBlock';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'asOfTimestamp';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                ];
              },
              {
                readonly name: 'marketData';
                readonly type: 'tuple';
                readonly internalType: 'struct INeverlandUiProvider.MarketData';
                readonly components: readonly [
                  {
                    readonly name: 'rewardTokens';
                    readonly type: 'address[]';
                    readonly internalType: 'address[]';
                  },
                  {
                    readonly name: 'rewardTokenBalances';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'distributionRates';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'nextEpochTimestamp';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'currentEpoch';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'epochRewards';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'nextEpochRewards';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'totalValueLockedUSD';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'followingEpochRewards';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'totalValueLockedUSDResolved';
                    readonly type: 'bool';
                    readonly internalType: 'bool';
                  },
                  {
                    readonly name: 'asOfBlock';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'asOfTimestamp';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                ];
              },
            ];
          },
          {
            readonly name: 'extended';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.ExtendedUserView';
            readonly components: readonly [
              {
                readonly name: 'unlockSchedule';
                readonly type: 'tuple';
                readonly internalType: 'struct INeverlandUiProvider.UnlockSchedule';
                readonly components: readonly [
                  {
                    readonly name: 'unlockTimes';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'amounts';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'tokenIds';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                ];
              },
              {
                readonly name: 'allPrices';
                readonly type: 'tuple';
                readonly internalType: 'struct INeverlandUiProvider.PriceData';
                readonly components: readonly [
                  {
                    readonly name: 'tokens';
                    readonly type: 'address[]';
                    readonly internalType: 'address[]';
                  },
                  {
                    readonly name: 'prices';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'lastUpdated';
                    readonly type: 'uint256[]';
                    readonly internalType: 'uint256[]';
                  },
                  {
                    readonly name: 'resolvedMask';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'dustPriceFromOracle';
                    readonly type: 'bool';
                    readonly internalType: 'bool';
                  },
                  {
                    readonly name: 'asOfBlock';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                  {
                    readonly name: 'asOfTimestamp';
                    readonly type: 'uint256';
                    readonly internalType: 'uint256';
                  },
                ];
              },
            ];
          },
          {
            readonly name: 'network';
            readonly type: 'tuple';
            readonly internalType: 'struct INeverlandUiProvider.NetworkData';
            readonly components: readonly [
              {
                readonly name: 'currentBlock';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'currentTimestamp';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'gasPrice';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
            ];
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getUnlockSchedule';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      {
        readonly name: 'unlockTimes';
        readonly type: 'uint256[]';
        readonly internalType: 'uint256[]';
      },
      { readonly name: 'amounts'; readonly type: 'uint256[]'; readonly internalType: 'uint256[]' },
      { readonly name: 'tokenIds'; readonly type: 'uint256[]'; readonly internalType: 'uint256[]' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getUserDashboard';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'offset'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'limit'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandUiProvider.UserDashboardData';
        readonly components: readonly [
          { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
          {
            readonly name: 'tokenIds';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'locks';
            readonly type: 'tuple[]';
            readonly internalType: 'struct INeverlandUiProvider.LockInfo[]';
            readonly components: readonly [
              {
                readonly name: 'tokenId';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'amount';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              { readonly name: 'end'; readonly type: 'uint256'; readonly internalType: 'uint256' },
              {
                readonly name: 'effectiveStart';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'isPermanent';
                readonly type: 'bool';
                readonly internalType: 'bool';
              },
              {
                readonly name: 'votingPower';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'rewardReceiver';
                readonly type: 'address';
                readonly internalType: 'address';
              },
              {
                readonly name: 'owner';
                readonly type: 'address';
                readonly internalType: 'address';
              },
            ];
          },
          {
            readonly name: 'rewardSummaries';
            readonly type: 'tuple[]';
            readonly internalType: 'struct INeverlandUiProvider.RewardSummary[]';
            readonly components: readonly [
              {
                readonly name: 'tokenId';
                readonly type: 'uint256';
                readonly internalType: 'uint256';
              },
              {
                readonly name: 'revenueRewards';
                readonly type: 'uint256[]';
                readonly internalType: 'uint256[]';
              },
              {
                readonly name: 'rewardTokens';
                readonly type: 'address[]';
                readonly internalType: 'address[]';
              },
            ];
          },
          {
            readonly name: 'totalVotingPower';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'totalLockedAmount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'rawTokenCount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'nextRawOffset';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'hasMore'; readonly type: 'bool'; readonly internalType: 'bool' },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getUserEmissionBreakdown';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'rewardToken'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      {
        readonly name: 'breakdown';
        readonly type: 'tuple[]';
        readonly internalType: 'struct INeverlandUiProvider.UserEmissionAsset[]';
        readonly components: readonly [
          { readonly name: 'asset'; readonly type: 'address'; readonly internalType: 'address' },
          { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          { readonly name: 'symbol'; readonly type: 'string'; readonly internalType: 'string' },
          { readonly name: 'isDebt'; readonly type: 'bool'; readonly internalType: 'bool' },
          { readonly name: 'resolved'; readonly type: 'bool'; readonly internalType: 'bool' },
        ];
      },
      {
        readonly name: 'enumerationResolved';
        readonly type: 'bool';
        readonly internalType: 'bool';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getUserEmissions';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      {
        readonly name: 'rewardTokens';
        readonly type: 'address[]';
        readonly internalType: 'address[]';
      },
      {
        readonly name: 'totalRewards';
        readonly type: 'uint256[]';
        readonly internalType: 'uint256[]';
      },
      { readonly name: 'resolved'; readonly type: 'bool'; readonly internalType: 'bool' },
      { readonly name: 'asOfBlock'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      {
        readonly name: 'asOfTimestamp';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getUserRewardsSummary';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: 'rewardTokens';
        readonly type: 'address[]';
        readonly internalType: 'address[]';
      },
    ];
    readonly outputs: readonly [
      {
        readonly name: 'summary';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandUiProvider.UserRewardsSummary';
        readonly components: readonly [
          {
            readonly name: 'totalRevenue';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'totalEmissions';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'revenueResolvedMask';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'emissionsResolvedMask';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'asOfBlock';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'asOfTimestamp';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getUserTokenCount';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      { readonly name: 'count'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'BalanceUnreadable';
    readonly inputs: readonly [
      { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'account'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
] satisfies Abi;
