// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import neverlandAssetRedemptionAbiJson from './neverlandAssetRedemptionAbi.json';

export const neverlandAssetRedemptionAbi = neverlandAssetRedemptionAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      {
        readonly name: 'fromToken_';
        readonly type: 'address';
        readonly internalType: 'contract IERC20';
      },
      {
        readonly name: 'toToken_';
        readonly type: 'address';
        readonly internalType: 'contract IERC20';
      },
      {
        readonly name: 'exchangeRate_';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'initialOwner_';
        readonly type: 'address';
        readonly internalType: 'address';
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'FROM_DENOMINATOR';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'FROM_TOKEN';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IERC20' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'TO_TOKEN';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IERC20' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'acceptOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'availableLiquidity';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'calculateRedeem';
    readonly inputs: readonly [
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: 'amountOut'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'exchangeRate';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'maxRedeemable';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'owner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'pause';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'paused';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'pendingOwner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'redeem';
    readonly inputs: readonly [
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: 'amountOut'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'renounceOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'setExchangeRate';
    readonly inputs: readonly [
      { readonly name: 'newRate'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'supply';
    readonly inputs: readonly [
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'totalPaid';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'totalRedeemed';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'transferOwnership';
    readonly inputs: readonly [
      { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'unpause';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'withdraw';
    readonly inputs: readonly [
      {
        readonly name: 'token';
        readonly type: 'address';
        readonly internalType: 'contract IERC20';
      },
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'event';
    readonly name: 'ExchangeRateChanged';
    readonly inputs: readonly [
      {
        readonly name: 'previousRate';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newRate';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferStarted';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferred';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'Paused';
    readonly inputs: readonly [
      {
        readonly name: 'account';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'Redeemed';
    readonly inputs: readonly [
      {
        readonly name: 'user';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'amountIn';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'amountOut';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'Supplied';
    readonly inputs: readonly [
      {
        readonly name: 'supplier';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'amount';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'Unpaused';
    readonly inputs: readonly [
      {
        readonly name: 'account';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'Withdrawn';
    readonly inputs: readonly [
      {
        readonly name: 'token';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'to';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'amount';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'EnforcedPause'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'ExpectedPause'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'InsufficientLiquidity'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'InvalidExchangeRate'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'OwnableInvalidOwner';
    readonly inputs: readonly [
      { readonly name: 'owner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'OwnableUnauthorizedAccount';
    readonly inputs: readonly [
      { readonly name: 'account'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  { readonly type: 'error'; readonly name: 'OwnershipRequired'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'ReentrancyGuardReentrantCall';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'SafeERC20FailedOperation';
    readonly inputs: readonly [
      { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  { readonly type: 'error'; readonly name: 'SameAddress'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'SourceTokenRecoveryLocked';
    readonly inputs: readonly [];
  },
  { readonly type: 'error'; readonly name: 'ZeroAmount'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'ZeroBalance'; readonly inputs: readonly [] },
] satisfies Abi;
