// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import neverlandPendleLeveragerAbiJson from './neverlandPendleLeveragerAbi.json';

export const neverlandPendleLeveragerAbi = neverlandPendleLeveragerAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      { readonly name: 'pool_'; readonly type: 'address'; readonly internalType: 'contract IPool' },
      { readonly name: 'debtAsset_'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'morpho_'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: 'flashPool_';
        readonly type: 'address';
        readonly internalType: 'contract IPool';
      },
      {
        readonly name: 'pendleRouter_';
        readonly type: 'address';
        readonly internalType: 'address';
      },
      { readonly name: 'market_'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: 'initialOwner_';
        readonly type: 'address';
        readonly internalType: 'address';
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'ADDRESSES_PROVIDER';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract IPoolAddressesProvider';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'A_PT';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'DEBT_ASSET';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'FLASH_POOL';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IPool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MARKET';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_ORACLE_DEVIATION_BPS';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MORPHO';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'PENDLE_ROUTER';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'POOL';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IPool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'PT';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'SY';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'YT';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'acceptOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'createPosition';
    readonly inputs: readonly [
      {
        readonly name: 'params';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.CreateParams';
        readonly components: readonly [
          {
            readonly name: 'initialPtAmount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'borrowAmount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'minPtOut'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'minHealthFactor';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'deadline'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly outputs: readonly [
      {
        readonly name: 'result';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.PositionResult';
        readonly components: readonly [
          {
            readonly name: 'principalSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptWithdrawn';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtBefore';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashBorrowed';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashRepaid';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'surplus'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'healthFactorAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'flashSource';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'flashCash';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'decreaseLeverage';
    readonly inputs: readonly [
      {
        readonly name: 'params';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.DecreaseParams';
        readonly components: readonly [
          { readonly name: 'ptAmount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'repayAmount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'maxCashRepaid';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'minDebtAssetOut';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'minHealthFactor';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'maxRounds';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'deadline'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly outputs: readonly [
      {
        readonly name: 'result';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.PositionResult';
        readonly components: readonly [
          {
            readonly name: 'principalSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptWithdrawn';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtBefore';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashBorrowed';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashRepaid';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'surplus'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'healthFactorAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'flashSource';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'flashCash';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'emergencyTokenTransfer';
    readonly inputs: readonly [
      { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'to'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'executeOperation';
    readonly inputs: readonly [
      { readonly name: 'assets'; readonly type: 'address[]'; readonly internalType: 'address[]' },
      { readonly name: 'amounts'; readonly type: 'uint256[]'; readonly internalType: 'uint256[]' },
      { readonly name: 'premiums'; readonly type: 'uint256[]'; readonly internalType: 'uint256[]' },
      { readonly name: 'initiator'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'data'; readonly type: 'bytes'; readonly internalType: 'bytes' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'flashCapacity';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'source'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'cash'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'flashPoolCapacity';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'increaseLeverage';
    readonly inputs: readonly [
      {
        readonly name: 'params';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.IncreaseParams';
        readonly components: readonly [
          {
            readonly name: 'borrowAmount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'minPtOut'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'minHealthFactor';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'deadline'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly outputs: readonly [
      {
        readonly name: 'result';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.PositionResult';
        readonly components: readonly [
          {
            readonly name: 'principalSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptWithdrawn';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtBefore';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashBorrowed';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashRepaid';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'surplus'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'healthFactorAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'flashSource';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'flashCash';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'leverageCapacity';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'onMorphoFlashLoan';
    readonly inputs: readonly [
      { readonly name: 'assets'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'data'; readonly type: 'bytes'; readonly internalType: 'bytes' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'owner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'pendingOwner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'previewCreatePosition';
    readonly inputs: readonly [
      {
        readonly name: 'params';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.CreateParams';
        readonly components: readonly [
          {
            readonly name: 'initialPtAmount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'borrowAmount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'minPtOut'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'minHealthFactor';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'deadline'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.PositionResult';
        readonly components: readonly [
          {
            readonly name: 'principalSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptWithdrawn';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtBefore';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashBorrowed';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashRepaid';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'surplus'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'healthFactorAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'flashSource';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'flashCash';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'previewDecreaseLeverage';
    readonly inputs: readonly [
      {
        readonly name: 'params';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.DecreaseParams';
        readonly components: readonly [
          { readonly name: 'ptAmount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'repayAmount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'maxCashRepaid';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'minDebtAssetOut';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'minHealthFactor';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'maxRounds';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'deadline'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.PositionResult';
        readonly components: readonly [
          {
            readonly name: 'principalSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptWithdrawn';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtBefore';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashBorrowed';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashRepaid';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'surplus'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'healthFactorAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'flashSource';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'flashCash';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'previewIncreaseLeverage';
    readonly inputs: readonly [
      {
        readonly name: 'params';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.IncreaseParams';
        readonly components: readonly [
          {
            readonly name: 'borrowAmount';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'minPtOut'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'minHealthFactor';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'deadline'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandPendleLeverager.PositionResult';
        readonly components: readonly [
          {
            readonly name: 'principalSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptSupplied';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'ptWithdrawn';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtBefore';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'debtAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashBorrowed';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'cashRepaid';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'surplus'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'healthFactorAfter';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'flashSource';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'flashCash';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'rounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        ];
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'renounceOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'simulate';
    readonly inputs: readonly [
      { readonly name: 'callData'; readonly type: 'bytes'; readonly internalType: 'bytes' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'transferOwnership';
    readonly inputs: readonly [
      { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'event';
    readonly name: 'ERC20Recovered';
    readonly inputs: readonly [
      {
        readonly name: 'token';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'to';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'amount';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'LeverageDecreased';
    readonly inputs: readonly [
      {
        readonly name: 'user';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'ptWithdrawn';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'cashRepaid';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'debtAfter';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'surplus';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'rounds';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'LeverageIncreased';
    readonly inputs: readonly [
      {
        readonly name: 'user';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'ptSupplied';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'cashBorrowed';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'debtAfter';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferStarted';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferred';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'PositionCreated';
    readonly inputs: readonly [
      {
        readonly name: 'user';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'principalSupplied';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'ptSupplied';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'cashBorrowed';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'debtAfter';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'error';
    readonly name: 'BalanceMismatch';
    readonly inputs: readonly [
      { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'expected'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'actual'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'CashRepaymentLimitExceeded';
    readonly inputs: readonly [
      { readonly name: 'required'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'remaining'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  { readonly type: 'error'; readonly name: 'CollateralNotEnabled'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'DeadlineExpired'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'DebtMismatch';
    readonly inputs: readonly [
      { readonly name: 'beforeDebt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'afterDebt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'FlashCallbackUnauthorized';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'HealthFactorBelowMinimum';
    readonly inputs: readonly [
      { readonly name: 'actual'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'minimum'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InsufficientFlashLiquidity';
    readonly inputs: readonly [
      { readonly name: 'required'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'available'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InsufficientPtBudget';
    readonly inputs: readonly [
      {
        readonly name: 'remainingRepayment';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      { readonly name: 'remainingPt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InsufficientRepaymentProceeds';
    readonly inputs: readonly [
      { readonly name: 'required'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'available'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  { readonly type: 'error'; readonly name: 'InvalidAmount'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'InvalidDependency';
    readonly inputs: readonly [
      { readonly name: 'dependency'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidMarket';
    readonly inputs: readonly [
      { readonly name: 'market'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidOraclePrice';
    readonly inputs: readonly [
      { readonly name: 'asset'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  { readonly type: 'error'; readonly name: 'InvalidSimulationCall'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'MarketExpired'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'OutputBelowMinimum';
    readonly inputs: readonly [
      { readonly name: 'output'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'minimum'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'OwnableInvalidOwner';
    readonly inputs: readonly [
      { readonly name: 'owner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'OwnableUnauthorizedAccount';
    readonly inputs: readonly [
      { readonly name: 'account'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  { readonly type: 'error'; readonly name: 'OwnershipRequired'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'ReentrancyGuardReentrantCall';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'ReserveIndexNotPar';
    readonly inputs: readonly [
      { readonly name: 'pt'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'ReserveNotListed';
    readonly inputs: readonly [
      { readonly name: 'asset'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'RoundLimitExceeded';
    readonly inputs: readonly [
      {
        readonly name: 'remainingRepayment';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      { readonly name: 'maxRounds'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'SafeERC20FailedOperation';
    readonly inputs: readonly [
      { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'UnsupportedSy';
    readonly inputs: readonly [
      { readonly name: 'sy'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
] satisfies Abi;
