// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import neverlandDustHelperAbiJson from './neverlandDustHelperAbi.json';

export const neverlandDustHelperAbi = neverlandDustHelperAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      { readonly name: '_dustToken'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: '_initialOwner';
        readonly type: 'address';
        readonly internalType: 'address';
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'DEFAULT_DUST_PRICE';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_TEAM_ADDRESSES';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'PRICE_DECIMALS';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint8'; readonly internalType: 'uint8' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'addTeamAddress';
    readonly inputs: readonly [
      { readonly name: 'teamAddress'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'addTeamAddresses';
    readonly inputs: readonly [
      {
        readonly name: 'teamAddressesBatch';
        readonly type: 'address[]';
        readonly internalType: 'address[]';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'decimals';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint8'; readonly internalType: 'uint8' },
    ];
    readonly stateMutability: 'pure';
  },
  {
    readonly type: 'function';
    readonly name: 'description';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'string'; readonly internalType: 'string' },
    ];
    readonly stateMutability: 'pure';
  },
  {
    readonly type: 'function';
    readonly name: 'dustPair';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'dustToken';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IERC20' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getAnswer';
    readonly inputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: 'answer'; readonly type: 'int256'; readonly internalType: 'int256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getCirculatingSupply';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'supply'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getDustValueInUSD';
    readonly inputs: readonly [
      { readonly name: 'dustAmount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: 'usdValue'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getMarketData';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: 'data';
        readonly type: 'tuple';
        readonly internalType: 'struct INeverlandDustHelper.MarketData';
        readonly components: readonly [
          {
            readonly name: 'circulatingSupply';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'totalSupply';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'usdPrice'; readonly type: 'uint256'; readonly internalType: 'uint256' },
          {
            readonly name: 'marketCap';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'fullyDilutedMarketCap';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'timestamp';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'isPriceFromOracle';
            readonly type: 'bool';
            readonly internalType: 'bool';
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getMarketMetrics';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: 'circulatingSupply';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      { readonly name: 'totalSupply'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'usdPrice'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'marketCap'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getPrice';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'price'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'fromOracle'; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getPriceInfo';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'price'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'isFromOracle'; readonly type: 'bool'; readonly internalType: 'bool' },
      { readonly name: 'lastUpdate'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'isStale'; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getRoundData';
    readonly inputs: readonly [
      { readonly name: 'requestRoundId'; readonly type: 'uint80'; readonly internalType: 'uint80' },
    ];
    readonly outputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint80'; readonly internalType: 'uint80' },
      { readonly name: 'answer'; readonly type: 'int256'; readonly internalType: 'int256' },
      { readonly name: 'startedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      {
        readonly name: 'answeredInRound';
        readonly type: 'uint80';
        readonly internalType: 'uint80';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getTeamAddressCount';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'count'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getTeamAddresses';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: 'addresses';
        readonly type: 'address[]';
        readonly internalType: 'address[]';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getTeamTotalBalance';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'balance'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getTimestamp';
    readonly inputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: 'timestamp'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getTotalSupply';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'supply'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getUSDValueInDust';
    readonly inputs: readonly [
      { readonly name: 'usdValue'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: 'dustAmount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getV4PriceExternal';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'price'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'success'; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getV4Slot0';
    readonly inputs: readonly [
      { readonly name: 'poolManager'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'poolId'; readonly type: 'bytes32'; readonly internalType: 'PoolId' },
    ];
    readonly outputs: readonly [
      { readonly name: 'sqrtPriceX96'; readonly type: 'uint160'; readonly internalType: 'uint160' },
      { readonly name: 'tick'; readonly type: 'int24'; readonly internalType: 'int24' },
      { readonly name: 'protocolFee'; readonly type: 'uint24'; readonly internalType: 'uint24' },
      { readonly name: 'lpFee'; readonly type: 'uint24'; readonly internalType: 'uint24' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'hardcodedPrice';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'isPriceCacheStale';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'isStale'; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'isTeamAddress';
    readonly inputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'lastPriceUpdate';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestAnswer';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'price'; readonly type: 'int256'; readonly internalType: 'int256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestRound';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestRoundData';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint80'; readonly internalType: 'uint80' },
      { readonly name: 'answer'; readonly type: 'int256'; readonly internalType: 'int256' },
      { readonly name: 'startedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      {
        readonly name: 'answeredInRound';
        readonly type: 'uint80';
        readonly internalType: 'uint80';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'latestTimestamp';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'timestamp'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'maxReasonablePrice';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'minReasonablePrice';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'owner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'pair';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'pairOracle';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'priceUpdateInterval';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'reclammIsDustToken0';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'reclammPool';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'removePair';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'removePairOracle';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'removeReclammPool';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'removeTeamAddress';
    readonly inputs: readonly [
      { readonly name: 'teamAddress'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'removeTeamAddresses';
    readonly inputs: readonly [
      {
        readonly name: 'teamAddressesBatch';
        readonly type: 'address[]';
        readonly internalType: 'address[]';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'removeV4Pool';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'renounceOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'setPair';
    readonly inputs: readonly [
      { readonly name: 'pairAddress'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'setPairOracle';
    readonly inputs: readonly [
      {
        readonly name: 'pairOracleAddress';
        readonly type: 'address';
        readonly internalType: 'address';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'setPriceLimits';
    readonly inputs: readonly [
      { readonly name: 'minPrice'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'maxPrice'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'setPriceUpdateInterval';
    readonly inputs: readonly [
      { readonly name: 'interval'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'setReclammPool';
    readonly inputs: readonly [
      { readonly name: 'pool'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'isDustToken0'; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'setV4Pool';
    readonly inputs: readonly [
      { readonly name: 'poolManager'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'poolId'; readonly type: 'bytes32'; readonly internalType: 'bytes32' },
      { readonly name: 'isDustToken0'; readonly type: 'bool'; readonly internalType: 'bool' },
      {
        readonly name: 'pairedCurrency';
        readonly type: 'address';
        readonly internalType: 'address';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'teamAddresses';
    readonly inputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'transferOwnership';
    readonly inputs: readonly [
      { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'updateHardcodedPrice';
    readonly inputs: readonly [
      { readonly name: 'newPrice'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'updatePriceCache';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'v4IsDustToken0';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'v4PairedCurrency';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'v4PoolId';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'bytes32'; readonly internalType: 'PoolId' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'v4PoolManager';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'version';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'pure';
  },
  {
    readonly type: 'event';
    readonly name: 'AnswerUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'current';
        readonly type: 'int256';
        readonly indexed: true;
        readonly internalType: 'int256';
      },
      {
        readonly name: 'roundId';
        readonly type: 'uint256';
        readonly indexed: true;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'updatedAt';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferred';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'PairOracleUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'oldPairOracle';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newPairOracle';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'PairUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'oldPair';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newPair';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'PriceLimitsUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'minPrice';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'maxPrice';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'PriceUpdateIntervalChanged';
    readonly inputs: readonly [
      {
        readonly name: 'oldInterval';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newInterval';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'PriceUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'oldPrice';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newPrice';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'timestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'fromOracle';
        readonly type: 'bool';
        readonly indexed: false;
        readonly internalType: 'bool';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'ReclammPoolRemoved';
    readonly inputs: readonly [];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'ReclammPoolUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'pool';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
      {
        readonly name: 'isDustToken0';
        readonly type: 'bool';
        readonly indexed: false;
        readonly internalType: 'bool';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'TeamAddressAdded';
    readonly inputs: readonly [
      {
        readonly name: 'teamAddress';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'TeamAddressRemoved';
    readonly inputs: readonly [
      {
        readonly name: 'teamAddress';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'TeamAddressesBatchAdded';
    readonly inputs: readonly [
      {
        readonly name: 'teamAddresses';
        readonly type: 'address[]';
        readonly indexed: false;
        readonly internalType: 'address[]';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'TeamAddressesBatchRemoved';
    readonly inputs: readonly [
      {
        readonly name: 'teamAddresses';
        readonly type: 'address[]';
        readonly indexed: false;
        readonly internalType: 'address[]';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'V4PoolRemoved';
    readonly inputs: readonly [];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'V4PoolUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'poolManager';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
      {
        readonly name: 'poolId';
        readonly type: 'bytes32';
        readonly indexed: false;
        readonly internalType: 'bytes32';
      },
      {
        readonly name: 'isDustToken0';
        readonly type: 'bool';
        readonly indexed: false;
        readonly internalType: 'bool';
      },
      {
        readonly name: 'pairedCurrency';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'EmptyArray'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'InvalidPrice';
    readonly inputs: readonly [
      { readonly name: 'price'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidPriceLimits';
    readonly inputs: readonly [
      { readonly name: 'minPrice'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'maxPrice'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidPriceUpdateInterval';
    readonly inputs: readonly [
      { readonly name: 'interval'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidReclammPoolConfig';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidRoundId';
    readonly inputs: readonly [
      { readonly name: 'roundId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  { readonly type: 'error'; readonly name: 'InvalidV4PoolConfig'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'NoDataPresent'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'NoRoundsRecorded'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'TeamAddressAlreadyExists';
    readonly inputs: readonly [
      { readonly name: 'teamAddress'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'TeamAddressNotFound';
    readonly inputs: readonly [
      { readonly name: 'teamAddress'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  { readonly type: 'error'; readonly name: 'TooManyTeamAddresses'; readonly inputs: readonly [] },
] satisfies Abi;
