// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import nftPartnershipRegistryAbiJson from './nftPartnershipRegistryAbi.json';

export const nftPartnershipRegistryAbi = nftPartnershipRegistryAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_DECAY_RATIO';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_FIRST_BONUS';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_STATIC_BOOST';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MIN_DECAY_RATIO';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MIN_FIRST_BONUS';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'addPartnership';
    readonly inputs: readonly [
      { readonly name: 'collection'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'name'; readonly type: 'string'; readonly internalType: 'string' },
      {
        readonly name: 'startTimestamp';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      { readonly name: 'endTimestamp'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      {
        readonly name: 'staticBoostBps';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'allPartnerships';
    readonly inputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'decayRatio';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'firstBonus';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getActivePartnerships';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: 'active'; readonly type: 'address[]'; readonly internalType: 'address[]' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getPartnership';
    readonly inputs: readonly [
      { readonly name: 'collection'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'tuple';
        readonly internalType: 'struct INFTPartnershipRegistry.Partnership';
        readonly components: readonly [
          {
            readonly name: 'collection';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          { readonly name: 'active'; readonly type: 'bool'; readonly internalType: 'bool' },
          {
            readonly name: 'startTimestamp';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'endTimestamp';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          { readonly name: 'name'; readonly type: 'string'; readonly internalType: 'string' },
          {
            readonly name: 'staticBoostBps';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getPartnershipCount';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'initialize';
    readonly inputs: readonly [
      {
        readonly name: '_initialOwner';
        readonly type: 'address';
        readonly internalType: 'address';
      },
      { readonly name: '_firstBonus'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: '_decayRatio'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'owner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'removePartnership';
    readonly inputs: readonly [
      { readonly name: 'collection'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'renounceOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'setMultiplierParams';
    readonly inputs: readonly [
      {
        readonly name: 'newFirstBonus';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newDecayRatio';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'transferOwnership';
    readonly inputs: readonly [
      { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'updatePartnership';
    readonly inputs: readonly [
      { readonly name: 'collection'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'active'; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'event';
    readonly name: 'Initialized';
    readonly inputs: readonly [
      {
        readonly name: 'version';
        readonly type: 'uint8';
        readonly indexed: false;
        readonly internalType: 'uint8';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'MultiplierParamsUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'oldFirstBonus';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newFirstBonus';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'oldDecayRatio';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newDecayRatio';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'timestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'totalActivePartnerships';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferred';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'PartnershipAdded';
    readonly inputs: readonly [
      {
        readonly name: 'collection';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'name';
        readonly type: 'string';
        readonly indexed: false;
        readonly internalType: 'string';
      },
      {
        readonly name: 'active';
        readonly type: 'bool';
        readonly indexed: false;
        readonly internalType: 'bool';
      },
      {
        readonly name: 'startTimestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'endTimestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'staticBoostBps';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'currentFirstBonus';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'currentDecayRatio';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'totalPartnerships';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'PartnershipRemoved';
    readonly inputs: readonly [
      {
        readonly name: 'collection';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'name';
        readonly type: 'string';
        readonly indexed: false;
        readonly internalType: 'string';
      },
      {
        readonly name: 'totalPartnerships';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'PartnershipUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'collection';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'name';
        readonly type: 'string';
        readonly indexed: false;
        readonly internalType: 'string';
      },
      {
        readonly name: 'active';
        readonly type: 'bool';
        readonly indexed: false;
        readonly internalType: 'bool';
      },
      {
        readonly name: 'startTimestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'endTimestamp';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'InvalidDecayRatio';
    readonly inputs: readonly [
      { readonly name: 'decayRatio'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidFirstBonus';
    readonly inputs: readonly [
      { readonly name: 'firstBonus'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidStaticBoost';
    readonly inputs: readonly [
      {
        readonly name: 'staticBoostBps';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
  },
  { readonly type: 'error'; readonly name: 'InvalidTimestamp'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'PartnershipAlreadyExists';
    readonly inputs: readonly [
      { readonly name: 'collection'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'PartnershipNotFound';
    readonly inputs: readonly [
      { readonly name: 'collection'; readonly type: 'address'; readonly internalType: 'address' },
    ];
  },
] satisfies Abi;
