// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import pendlePtDiscountOracleAdapterAbiJson from './pendlePtDiscountOracleAdapterAbi.json';

export const pendlePtDiscountOracleAdapterAbi =
  pendlePtDiscountOracleAdapterAbiJson as unknown as readonly [
    {
      readonly type: 'constructor';
      readonly inputs: readonly [
        {
          readonly name: '_baseAggregator';
          readonly type: 'address';
          readonly internalType: 'address';
        },
        {
          readonly name: '_principalToken';
          readonly type: 'address';
          readonly internalType: 'address';
        },
        { readonly name: '_maxDelay'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        {
          readonly name: '_maxDiscountRatePerYear';
          readonly type: 'uint16';
          readonly internalType: 'uint16';
        },
        {
          readonly name: '_discountRatePerYear';
          readonly type: 'uint16';
          readonly internalType: 'uint16';
        },
        { readonly name: '_description'; readonly type: 'string'; readonly internalType: 'string' },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'acceptOwnership';
      readonly inputs: readonly [];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'baseAggregator';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'address';
          readonly internalType: 'contract AggregatorV3Interface';
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'baseDecimals';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint8'; readonly internalType: 'uint8' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'decimals';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint8'; readonly internalType: 'uint8' },
      ];
      readonly stateMutability: 'pure';
    },
    {
      readonly type: 'function';
      readonly name: 'description';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'string'; readonly internalType: 'string' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'discountRatePerYear';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint16'; readonly internalType: 'uint16' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getAnswer';
      readonly inputs: readonly [
        { readonly name: 'roundId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'int256'; readonly internalType: 'int256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getCurrentDiscount';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getRoundData';
      readonly inputs: readonly [
        {
          readonly name: 'requestedRoundId';
          readonly type: 'uint80';
          readonly internalType: 'uint80';
        },
      ];
      readonly outputs: readonly [
        { readonly name: 'roundId'; readonly type: 'uint80'; readonly internalType: 'uint80' },
        { readonly name: 'answer'; readonly type: 'int256'; readonly internalType: 'int256' },
        { readonly name: 'startedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        {
          readonly name: 'answeredInRound';
          readonly type: 'uint80';
          readonly internalType: 'uint80';
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getTimestamp';
      readonly inputs: readonly [
        { readonly name: 'roundId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'latestAnswer';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'int256'; readonly internalType: 'int256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'latestRound';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'latestRoundData';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: 'roundId'; readonly type: 'uint80'; readonly internalType: 'uint80' },
        { readonly name: 'answer'; readonly type: 'int256'; readonly internalType: 'int256' },
        { readonly name: 'startedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        {
          readonly name: 'answeredInRound';
          readonly type: 'uint80';
          readonly internalType: 'uint80';
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'latestTimestamp';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'maturity';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'maxDelay';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'maxDiscountRatePerYear';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint16'; readonly internalType: 'uint16' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'owner';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'pendingOwner';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'principalToken';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'address';
          readonly internalType: 'contract IPendlePrincipalToken';
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'renounceOwnership';
      readonly inputs: readonly [];
      readonly outputs: readonly [];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'setDiscountRatePerYear';
      readonly inputs: readonly [
        {
          readonly name: 'newRatePerYear';
          readonly type: 'uint16';
          readonly internalType: 'uint16';
        },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'transferOwnership';
      readonly inputs: readonly [
        { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'version';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'pure';
    },
    {
      readonly type: 'event';
      readonly name: 'AnswerUpdated';
      readonly inputs: readonly [
        {
          readonly name: 'current';
          readonly type: 'int256';
          readonly indexed: true;
          readonly internalType: 'int256';
        },
        {
          readonly name: 'roundId';
          readonly type: 'uint256';
          readonly indexed: true;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'updatedAt';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'DiscountRatePerYearUpdated';
      readonly inputs: readonly [
        {
          readonly name: 'previousRatePerYear';
          readonly type: 'uint16';
          readonly indexed: false;
          readonly internalType: 'uint16';
        },
        {
          readonly name: 'newRatePerYear';
          readonly type: 'uint16';
          readonly indexed: false;
          readonly internalType: 'uint16';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'NewRound';
      readonly inputs: readonly [
        {
          readonly name: 'roundId';
          readonly type: 'uint256';
          readonly indexed: true;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'startedBy';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'startedAt';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'OwnershipTransferStarted';
      readonly inputs: readonly [
        {
          readonly name: 'previousOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'newOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'OwnershipTransferred';
      readonly inputs: readonly [
        {
          readonly name: 'previousOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'newOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
      ];
      readonly anonymous: false;
    },
    { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
    {
      readonly type: 'error';
      readonly name: 'DiscountExceedsHundredPercent';
      readonly inputs: readonly [];
    },
    { readonly type: 'error'; readonly name: 'InvalidBasePrice'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'InvalidDecimals'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'InvalidDiscountRate'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'InvalidPtPrice'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'MaturityHasPassed'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'OwnershipRequired'; readonly inputs: readonly [] },
    {
      readonly type: 'error';
      readonly name: 'PriceTooOld';
      readonly inputs: readonly [
        {
          readonly name: 'currentTime';
          readonly type: 'uint256';
          readonly internalType: 'uint256';
        },
        { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'maxTime'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
    },
    { readonly type: 'error'; readonly name: 'StaleRound'; readonly inputs: readonly [] },
  ] satisfies Abi;
