// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import poolAddressesProviderRegistryAbiJson from './poolAddressesProviderRegistryAbi.json';

export const poolAddressesProviderRegistryAbi =
  poolAddressesProviderRegistryAbiJson as unknown as readonly [
    {
      readonly inputs: readonly [
        { readonly internalType: 'address'; readonly name: 'owner'; readonly type: 'address' },
      ];
      readonly stateMutability: 'nonpayable';
      readonly type: 'constructor';
    },
    {
      readonly anonymous: false;
      readonly inputs: readonly [
        {
          readonly indexed: true;
          readonly internalType: 'address';
          readonly name: 'addressesProvider';
          readonly type: 'address';
        },
        {
          readonly indexed: true;
          readonly internalType: 'uint256';
          readonly name: 'id';
          readonly type: 'uint256';
        },
      ];
      readonly name: 'AddressesProviderRegistered';
      readonly type: 'event';
    },
    {
      readonly anonymous: false;
      readonly inputs: readonly [
        {
          readonly indexed: true;
          readonly internalType: 'address';
          readonly name: 'addressesProvider';
          readonly type: 'address';
        },
        {
          readonly indexed: true;
          readonly internalType: 'uint256';
          readonly name: 'id';
          readonly type: 'uint256';
        },
      ];
      readonly name: 'AddressesProviderUnregistered';
      readonly type: 'event';
    },
    {
      readonly anonymous: false;
      readonly inputs: readonly [
        {
          readonly indexed: true;
          readonly internalType: 'address';
          readonly name: 'previousOwner';
          readonly type: 'address';
        },
        {
          readonly indexed: true;
          readonly internalType: 'address';
          readonly name: 'newOwner';
          readonly type: 'address';
        },
      ];
      readonly name: 'OwnershipTransferred';
      readonly type: 'event';
    },
    {
      readonly inputs: readonly [
        { readonly internalType: 'uint256'; readonly name: 'id'; readonly type: 'uint256' },
      ];
      readonly name: 'getAddressesProviderAddressById';
      readonly outputs: readonly [
        { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [
        {
          readonly internalType: 'address';
          readonly name: 'addressesProvider';
          readonly type: 'address';
        },
      ];
      readonly name: 'getAddressesProviderIdByAddress';
      readonly outputs: readonly [
        { readonly internalType: 'uint256'; readonly name: ''; readonly type: 'uint256' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'getAddressesProvidersList';
      readonly outputs: readonly [
        { readonly internalType: 'address[]'; readonly name: ''; readonly type: 'address[]' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'owner';
      readonly outputs: readonly [
        { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
      ];
      readonly stateMutability: 'view';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [
        { readonly internalType: 'address'; readonly name: 'provider'; readonly type: 'address' },
        { readonly internalType: 'uint256'; readonly name: 'id'; readonly type: 'uint256' },
      ];
      readonly name: 'registerAddressesProvider';
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [];
      readonly name: 'renounceOwnership';
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [
        { readonly internalType: 'address'; readonly name: 'newOwner'; readonly type: 'address' },
      ];
      readonly name: 'transferOwnership';
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
      readonly type: 'function';
    },
    {
      readonly inputs: readonly [
        { readonly internalType: 'address'; readonly name: 'provider'; readonly type: 'address' },
      ];
      readonly name: 'unregisterAddressesProvider';
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
      readonly type: 'function';
    },
  ] satisfies Abi;
