// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import staticATokenFactoryAbiJson from './staticATokenFactoryAbi.json';

export const staticATokenFactoryAbi = staticATokenFactoryAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      { readonly name: 'pool'; readonly type: 'address'; readonly internalType: 'contract IPool' },
      { readonly name: 'proxyAdmin'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: 'transparentProxyFactory';
        readonly type: 'address';
        readonly internalType: 'contract ITransparentProxyFactory';
      },
      {
        readonly name: 'staticATokenImpl';
        readonly type: 'address';
        readonly internalType: 'address';
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'ADMIN';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'POOL';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IPool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'STATIC_A_TOKEN_IMPL';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'TRANSPARENT_PROXY_FACTORY';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract ITransparentProxyFactory';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'createStaticATokens';
    readonly inputs: readonly [
      {
        readonly name: 'underlyings';
        readonly type: 'address[]';
        readonly internalType: 'address[]';
      },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address[]'; readonly internalType: 'address[]' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'getStaticAToken';
    readonly inputs: readonly [
      { readonly name: 'underlying'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getStaticATokens';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address[]'; readonly internalType: 'address[]' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'initialize';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'event';
    readonly name: 'Initialized';
    readonly inputs: readonly [
      {
        readonly name: 'version';
        readonly type: 'uint8';
        readonly indexed: false;
        readonly internalType: 'uint8';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'StaticTokenCreated';
    readonly inputs: readonly [
      {
        readonly name: 'staticAToken';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'underlying';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
] satisfies Abi;
