// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import stataOracleAbiJson from './stataOracleAbi.json';

export const stataOracleAbi = stataOracleAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      {
        readonly name: 'provider';
        readonly type: 'address';
        readonly internalType: 'contract IPoolAddressesProvider';
      },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'AAVE_ORACLE';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract IAaveOracle';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'POOL';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IPool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getAssetPrice';
    readonly inputs: readonly [
      { readonly name: 'asset'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getAssetsPrices';
    readonly inputs: readonly [
      { readonly name: 'assets'; readonly type: 'address[]'; readonly internalType: 'address[]' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256[]'; readonly internalType: 'uint256[]' },
    ];
    readonly stateMutability: 'view';
  },
] satisfies Abi;
