// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import uiIncentiveDataProviderV3AbiJson from './uiIncentiveDataProviderV3Abi.json';

export const uiIncentiveDataProviderV3Abi =
  uiIncentiveDataProviderV3AbiJson as unknown as readonly [
    {
      readonly type: 'function';
      readonly name: 'getFullReservesIncentiveData';
      readonly inputs: readonly [
        {
          readonly name: 'provider';
          readonly type: 'address';
          readonly internalType: 'contract IPoolAddressesProvider';
        },
        { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple[]';
          readonly internalType: 'struct IUiIncentiveDataProviderV3.AggregatedReserveIncentiveData[]';
          readonly components: readonly [
            {
              readonly name: 'underlyingAsset';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'aIncentiveData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.IncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'rewardsTokenInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.RewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'emissionPerSecond';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'incentivesLastUpdateTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'emissionEndTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'precision';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
            {
              readonly name: 'vIncentiveData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.IncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'rewardsTokenInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.RewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'emissionPerSecond';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'incentivesLastUpdateTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'emissionEndTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'precision';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
            {
              readonly name: 'sIncentiveData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.IncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'rewardsTokenInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.RewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'emissionPerSecond';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'incentivesLastUpdateTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'emissionEndTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'precision';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
          ];
        },
        {
          readonly name: '';
          readonly type: 'tuple[]';
          readonly internalType: 'struct IUiIncentiveDataProviderV3.UserReserveIncentiveData[]';
          readonly components: readonly [
            {
              readonly name: 'underlyingAsset';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'aTokenIncentivesUserData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.UserIncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'userRewardsInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.UserRewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'userUnclaimedRewards';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesUserIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
            {
              readonly name: 'vTokenIncentivesUserData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.UserIncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'userRewardsInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.UserRewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'userUnclaimedRewards';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesUserIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
            {
              readonly name: 'sTokenIncentivesUserData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.UserIncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'userRewardsInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.UserRewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'userUnclaimedRewards';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesUserIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
          ];
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getReservesIncentivesData';
      readonly inputs: readonly [
        {
          readonly name: 'provider';
          readonly type: 'address';
          readonly internalType: 'contract IPoolAddressesProvider';
        },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple[]';
          readonly internalType: 'struct IUiIncentiveDataProviderV3.AggregatedReserveIncentiveData[]';
          readonly components: readonly [
            {
              readonly name: 'underlyingAsset';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'aIncentiveData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.IncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'rewardsTokenInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.RewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'emissionPerSecond';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'incentivesLastUpdateTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'emissionEndTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'precision';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
            {
              readonly name: 'vIncentiveData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.IncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'rewardsTokenInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.RewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'emissionPerSecond';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'incentivesLastUpdateTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'emissionEndTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'precision';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
            {
              readonly name: 'sIncentiveData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.IncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'rewardsTokenInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.RewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'emissionPerSecond';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'incentivesLastUpdateTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'emissionEndTimestamp';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'precision';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
          ];
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getUserReservesIncentivesData';
      readonly inputs: readonly [
        {
          readonly name: 'provider';
          readonly type: 'address';
          readonly internalType: 'contract IPoolAddressesProvider';
        },
        { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'tuple[]';
          readonly internalType: 'struct IUiIncentiveDataProviderV3.UserReserveIncentiveData[]';
          readonly components: readonly [
            {
              readonly name: 'underlyingAsset';
              readonly type: 'address';
              readonly internalType: 'address';
            },
            {
              readonly name: 'aTokenIncentivesUserData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.UserIncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'userRewardsInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.UserRewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'userUnclaimedRewards';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesUserIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
            {
              readonly name: 'vTokenIncentivesUserData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.UserIncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'userRewardsInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.UserRewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'userUnclaimedRewards';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesUserIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
            {
              readonly name: 'sTokenIncentivesUserData';
              readonly type: 'tuple';
              readonly internalType: 'struct IUiIncentiveDataProviderV3.UserIncentiveData';
              readonly components: readonly [
                {
                  readonly name: 'tokenAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'incentiveControllerAddress';
                  readonly type: 'address';
                  readonly internalType: 'address';
                },
                {
                  readonly name: 'userRewardsInformation';
                  readonly type: 'tuple[]';
                  readonly internalType: 'struct IUiIncentiveDataProviderV3.UserRewardInfo[]';
                  readonly components: readonly [
                    {
                      readonly name: 'rewardTokenSymbol';
                      readonly type: 'string';
                      readonly internalType: 'string';
                    },
                    {
                      readonly name: 'rewardOracleAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'rewardTokenAddress';
                      readonly type: 'address';
                      readonly internalType: 'address';
                    },
                    {
                      readonly name: 'userUnclaimedRewards';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'tokenIncentivesUserIndex';
                      readonly type: 'uint256';
                      readonly internalType: 'uint256';
                    },
                    {
                      readonly name: 'rewardPriceFeed';
                      readonly type: 'int256';
                      readonly internalType: 'int256';
                    },
                    {
                      readonly name: 'priceFeedDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                    {
                      readonly name: 'rewardTokenDecimals';
                      readonly type: 'uint8';
                      readonly internalType: 'uint8';
                    },
                  ];
                },
              ];
            },
          ];
        },
      ];
      readonly stateMutability: 'view';
    },
  ] satisfies Abi;
