// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import userVaultAbiJson from './userVaultAbi.json';

export const userVaultAbi = userVaultAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'depositCollateral';
    readonly inputs: readonly [
      {
        readonly name: 'poolAddressesProvider';
        readonly type: 'address';
        readonly internalType: 'address';
      },
      { readonly name: 'debtToken'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'getTokenIdsReward';
    readonly inputs: readonly [
      { readonly name: 'tokenIds'; readonly type: 'uint256[]'; readonly internalType: 'uint256[]' },
      { readonly name: 'rewardToken'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'initialize';
    readonly inputs: readonly [
      { readonly name: '_user'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: '_revenueReward';
        readonly type: 'address';
        readonly internalType: 'contract IRevenueReward';
      },
      {
        readonly name: '_userVaultRegistry';
        readonly type: 'address';
        readonly internalType: 'contract IUserVaultRegistry';
      },
      {
        readonly name: '_poolAddressesProviderRegistry';
        readonly type: 'address';
        readonly internalType: 'contract IPoolAddressesProviderRegistry';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'poolAddressesProviderRegistry';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract IPoolAddressesProviderRegistry';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'recoverERC20';
    readonly inputs: readonly [
      { readonly name: 'token'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'recoverETH';
    readonly inputs: readonly [
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'repayDebt';
    readonly inputs: readonly [
      {
        readonly name: 'poolAddressesProvider';
        readonly type: 'address';
        readonly internalType: 'address';
      },
      { readonly name: 'debtToken'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'amount'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'repayUserDebt';
    readonly inputs: readonly [
      {
        readonly name: 'params';
        readonly type: 'tuple';
        readonly internalType: 'struct IUserVault.RepayUserDebtParams';
        readonly components: readonly [
          {
            readonly name: 'debtToken';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'poolAddressesProvider';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'tokenIds';
            readonly type: 'uint256[]';
            readonly internalType: 'uint256[]';
          },
          {
            readonly name: 'rewardToken';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'rewardTokenAmountToSwap';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'aggregatorAddress';
            readonly type: 'address';
            readonly internalType: 'address';
          },
          {
            readonly name: 'aggregatorData';
            readonly type: 'bytes';
            readonly internalType: 'bytes';
          },
          {
            readonly name: 'maxSlippageBps';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
        ];
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'revenueReward';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract IRevenueReward';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'swapAndVerify';
    readonly inputs: readonly [
      { readonly name: 'tokenIn'; readonly type: 'address'; readonly internalType: 'address' },
      {
        readonly name: 'tokenInAmount';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      { readonly name: 'tokenOut'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'aggregator'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'aggregatorData'; readonly type: 'bytes'; readonly internalType: 'bytes' },
      {
        readonly name: 'poolAddressesProvider';
        readonly type: 'address';
        readonly internalType: 'address';
      },
      {
        readonly name: 'maxAllowedSlippageBps';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'user';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'userVaultRegistry';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'address';
        readonly internalType: 'contract IUserVaultRegistry';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'event';
    readonly name: 'Initialized';
    readonly inputs: readonly [
      {
        readonly name: 'version';
        readonly type: 'uint8';
        readonly indexed: false;
        readonly internalType: 'uint8';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'LoanSelfRepaid';
    readonly inputs: readonly [
      {
        readonly name: 'user';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'userVault';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'poolAddressesProvider';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
      {
        readonly name: 'debtToken';
        readonly type: 'address';
        readonly indexed: false;
        readonly internalType: 'address';
      },
      {
        readonly name: 'amount';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'AggregatorNotSupported'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'ETHSendFailed'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'GettingAssetPriceFailed';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidPoolAddressesProvider';
    readonly inputs: readonly [];
  },
  {
    readonly type: 'error';
    readonly name: 'InvalidUserVaultForToken';
    readonly inputs: readonly [];
  },
  { readonly type: 'error'; readonly name: 'MaxSlippageTooHigh'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'NotExecutor'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'SlippageExceeded'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'SwapFailed'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'UnauthorizedAccess'; readonly inputs: readonly [] },
  { readonly type: 'error'; readonly name: 'ZeroAmount'; readonly inputs: readonly [] },
] satisfies Abi;
