// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import userVaultRegistryAbiJson from './userVaultRegistryAbi.json';

export const userVaultRegistryAbi = userVaultRegistryAbiJson as unknown as readonly [
  {
    readonly type: 'function';
    readonly name: 'acceptOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'executor';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'isSupportedAggregator';
    readonly inputs: readonly [
      { readonly name: 'aggregator'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'maxSwapSlippageBps';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'owner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'pendingOwner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'renounceOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'setExecutor';
    readonly inputs: readonly [
      { readonly name: '_executor'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'setMaxSwapSlippageBps';
    readonly inputs: readonly [
      {
        readonly name: 'newMaxSwapSlippageBps';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'setSupportedAggregators';
    readonly inputs: readonly [
      { readonly name: 'aggregator'; readonly type: 'address'; readonly internalType: 'address' },
      { readonly name: 'isActive'; readonly type: 'bool'; readonly internalType: 'bool' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'transferOwnership';
    readonly inputs: readonly [
      { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'event';
    readonly name: 'AggregatorSupportUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'aggregator';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'isActive';
        readonly type: 'bool';
        readonly indexed: false;
        readonly internalType: 'bool';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'ExecutorUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'oldExecutor';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newExecutor';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'MaxSwapSlippageUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'oldValue';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newValue';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferStarted';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferred';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
] satisfies Abi;
