// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import votingPowerMultiplierAbiJson from './votingPowerMultiplierAbi.json';

export const votingPowerMultiplierAbi = votingPowerMultiplierAbiJson as unknown as readonly [
  {
    readonly type: 'constructor';
    readonly inputs: readonly [
      { readonly name: '_dustLock'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'MAX_MULTIPLIER_BPS';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'MIN_MULTIPLIER_BPS';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'addTier';
    readonly inputs: readonly [
      {
        readonly name: 'minVotingPower';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'multiplierBps';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'dustLock';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IDustLock' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getAllTiers';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'tuple[]';
        readonly internalType: 'struct IVotingPowerMultiplier.VotingPowerTier[]';
        readonly components: readonly [
          {
            readonly name: 'minVotingPower';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'multiplierBps';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getMultiplierForVotingPower';
    readonly inputs: readonly [
      { readonly name: 'votingPower'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      {
        readonly name: 'multiplierBps';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getTier';
    readonly inputs: readonly [
      { readonly name: 'tierIndex'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [
      {
        readonly name: '';
        readonly type: 'tuple';
        readonly internalType: 'struct IVotingPowerMultiplier.VotingPowerTier';
        readonly components: readonly [
          {
            readonly name: 'minVotingPower';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
          {
            readonly name: 'multiplierBps';
            readonly type: 'uint256';
            readonly internalType: 'uint256';
          },
        ];
      },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getTierCount';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'getUserMultiplier';
    readonly inputs: readonly [
      { readonly name: 'user'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [
      {
        readonly name: 'multiplierBps';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      { readonly name: 'votingPower'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      { readonly name: 'tokenId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'initialize';
    readonly inputs: readonly [
      {
        readonly name: '_initialOwner';
        readonly type: 'address';
        readonly internalType: 'address';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'owner';
    readonly inputs: readonly [];
    readonly outputs: readonly [
      { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'removeTier';
    readonly inputs: readonly [
      { readonly name: 'tierIndex'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'renounceOwnership';
    readonly inputs: readonly [];
    readonly outputs: readonly [];
    readonly stateMutability: 'view';
  },
  {
    readonly type: 'function';
    readonly name: 'transferOwnership';
    readonly inputs: readonly [
      { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'function';
    readonly name: 'updateTier';
    readonly inputs: readonly [
      { readonly name: 'tierIndex'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      {
        readonly name: 'minVotingPower';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'multiplierBps';
        readonly type: 'uint256';
        readonly internalType: 'uint256';
      },
    ];
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
  },
  {
    readonly type: 'event';
    readonly name: 'Initialized';
    readonly inputs: readonly [
      {
        readonly name: 'version';
        readonly type: 'uint8';
        readonly indexed: false;
        readonly internalType: 'uint8';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'OwnershipTransferred';
    readonly inputs: readonly [
      {
        readonly name: 'previousOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
      {
        readonly name: 'newOwner';
        readonly type: 'address';
        readonly indexed: true;
        readonly internalType: 'address';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'TierAdded';
    readonly inputs: readonly [
      {
        readonly name: 'tierIndex';
        readonly type: 'uint256';
        readonly indexed: true;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'minVotingPower';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'multiplierBps';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'totalTiers';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'TierRemoved';
    readonly inputs: readonly [
      {
        readonly name: 'tierIndex';
        readonly type: 'uint256';
        readonly indexed: true;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'totalTiers';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  {
    readonly type: 'event';
    readonly name: 'TierUpdated';
    readonly inputs: readonly [
      {
        readonly name: 'tierIndex';
        readonly type: 'uint256';
        readonly indexed: true;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'oldMinVotingPower';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newMinVotingPower';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'oldMultiplierBps';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
      {
        readonly name: 'newMultiplierBps';
        readonly type: 'uint256';
        readonly indexed: false;
        readonly internalType: 'uint256';
      },
    ];
    readonly anonymous: false;
  },
  { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
  {
    readonly type: 'error';
    readonly name: 'InvalidTierIndex';
    readonly inputs: readonly [
      { readonly name: 'tierIndex'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  {
    readonly type: 'error';
    readonly name: 'MultiplierTooHigh';
    readonly inputs: readonly [
      { readonly name: 'multiplier'; readonly type: 'uint256'; readonly internalType: 'uint256' },
    ];
  },
  { readonly type: 'error'; readonly name: 'TiersNotAscending'; readonly inputs: readonly [] },
] satisfies Abi;
