// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import wethGatewayLegacyAbiJson from './wethGatewayLegacyAbi.json';

export const wethGatewayLegacyAbi = wethGatewayLegacyAbiJson as unknown as readonly [
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'weth'; readonly type: 'address' },
      { readonly internalType: 'address'; readonly name: 'owner'; readonly type: 'address' },
      { readonly internalType: 'contract IPool'; readonly name: 'pool'; readonly type: 'address' },
    ];
    readonly stateMutability: 'nonpayable';
    readonly type: 'constructor';
  },
  {
    readonly anonymous: false;
    readonly inputs: readonly [
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'previousOwner';
        readonly type: 'address';
      },
      {
        readonly indexed: true;
        readonly internalType: 'address';
        readonly name: 'newOwner';
        readonly type: 'address';
      },
    ];
    readonly name: 'OwnershipTransferred';
    readonly type: 'event';
  },
  { readonly stateMutability: 'payable'; readonly type: 'fallback' },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'amount'; readonly type: 'uint256' },
      {
        readonly internalType: 'uint256';
        readonly name: 'interestRateMode';
        readonly type: 'uint256';
      },
      { readonly internalType: 'uint16'; readonly name: 'referralCode'; readonly type: 'uint16' },
    ];
    readonly name: 'borrowETH';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
      { readonly internalType: 'address'; readonly name: 'onBehalfOf'; readonly type: 'address' },
      { readonly internalType: 'uint16'; readonly name: 'referralCode'; readonly type: 'uint16' },
    ];
    readonly name: 'depositETH';
    readonly outputs: readonly [];
    readonly stateMutability: 'payable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'to'; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'amount'; readonly type: 'uint256' },
    ];
    readonly name: 'emergencyEtherTransfer';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'token'; readonly type: 'address' },
      { readonly internalType: 'address'; readonly name: 'to'; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'amount'; readonly type: 'uint256' },
    ];
    readonly name: 'emergencyTokenTransfer';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'getWETHAddress';
    readonly outputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'owner';
    readonly outputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
    ];
    readonly stateMutability: 'view';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [];
    readonly name: 'renounceOwnership';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'amount'; readonly type: 'uint256' },
      { readonly internalType: 'uint256'; readonly name: 'rateMode'; readonly type: 'uint256' },
      { readonly internalType: 'address'; readonly name: 'onBehalfOf'; readonly type: 'address' },
    ];
    readonly name: 'repayETH';
    readonly outputs: readonly [];
    readonly stateMutability: 'payable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: 'newOwner'; readonly type: 'address' },
    ];
    readonly name: 'transferOwnership';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'amount'; readonly type: 'uint256' },
      { readonly internalType: 'address'; readonly name: 'to'; readonly type: 'address' },
    ];
    readonly name: 'withdrawETH';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  {
    readonly inputs: readonly [
      { readonly internalType: 'address'; readonly name: ''; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'amount'; readonly type: 'uint256' },
      { readonly internalType: 'address'; readonly name: 'to'; readonly type: 'address' },
      { readonly internalType: 'uint256'; readonly name: 'deadline'; readonly type: 'uint256' },
      { readonly internalType: 'uint8'; readonly name: 'permitV'; readonly type: 'uint8' },
      { readonly internalType: 'bytes32'; readonly name: 'permitR'; readonly type: 'bytes32' },
      { readonly internalType: 'bytes32'; readonly name: 'permitS'; readonly type: 'bytes32' },
    ];
    readonly name: 'withdrawETHWithPermit';
    readonly outputs: readonly [];
    readonly stateMutability: 'nonpayable';
    readonly type: 'function';
  },
  { readonly stateMutability: 'payable'; readonly type: 'receive' },
] satisfies Abi;
