// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type { Abi } from 'abitype';
import yieldBearingOracleAdapterAbiJson from './yieldBearingOracleAdapterAbi.json';

export const yieldBearingOracleAdapterAbi =
  yieldBearingOracleAdapterAbiJson as unknown as readonly [
    {
      readonly type: 'constructor';
      readonly inputs: readonly [
        {
          readonly name: '_baseAggregator';
          readonly type: 'address';
          readonly internalType: 'address';
        },
        {
          readonly name: '_sharesContract';
          readonly type: 'address';
          readonly internalType: 'address';
        },
        { readonly name: '_maxDelay'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        {
          readonly name: '_minimumSnapshotDelay';
          readonly type: 'uint48';
          readonly internalType: 'uint48';
        },
        {
          readonly name: '_maximumSnapshotAge';
          readonly type: 'uint48';
          readonly internalType: 'uint48';
        },
        {
          readonly name: '_initialRejectionGraceBps';
          readonly type: 'uint16';
          readonly internalType: 'uint16';
        },
        { readonly name: '_description'; readonly type: 'string'; readonly internalType: 'string' },
      ];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'acceptOwnership';
      readonly inputs: readonly [];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'assetDecimals';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint8'; readonly internalType: 'uint8' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'baseAggregator';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        {
          readonly name: '';
          readonly type: 'address';
          readonly internalType: 'contract AggregatorV3Interface';
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'baseDecimals';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint8'; readonly internalType: 'uint8' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'decimals';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint8'; readonly internalType: 'uint8' },
      ];
      readonly stateMutability: 'pure';
    },
    {
      readonly type: 'function';
      readonly name: 'description';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'string'; readonly internalType: 'string' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getAnswer';
      readonly inputs: readonly [
        { readonly name: 'roundId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'int256'; readonly internalType: 'int256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getCurrentSlackBps';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: 'slackBps'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'ok'; readonly type: 'bool'; readonly internalType: 'bool' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getGrowthRatePerSecond';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getMaxAnnualGrowthBps';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getRejectionGraceBps';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getRoundData';
      readonly inputs: readonly [
        {
          readonly name: 'requestedRoundId';
          readonly type: 'uint80';
          readonly internalType: 'uint80';
        },
      ];
      readonly outputs: readonly [
        { readonly name: 'roundId'; readonly type: 'uint80'; readonly internalType: 'uint80' },
        { readonly name: 'answer'; readonly type: 'int256'; readonly internalType: 'int256' },
        { readonly name: 'startedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        {
          readonly name: 'answeredInRound';
          readonly type: 'uint80';
          readonly internalType: 'uint80';
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getSnapshotRatio';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getSnapshotTimestamp';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'getTimestamp';
      readonly inputs: readonly [
        { readonly name: 'roundId'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'isCapped';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'bool'; readonly internalType: 'bool' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'keeper';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'latestAnswer';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'int256'; readonly internalType: 'int256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'latestRound';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'latestRoundData';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: 'roundId'; readonly type: 'uint80'; readonly internalType: 'uint80' },
        { readonly name: 'answer'; readonly type: 'int256'; readonly internalType: 'int256' },
        { readonly name: 'startedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        {
          readonly name: 'answeredInRound';
          readonly type: 'uint80';
          readonly internalType: 'uint80';
        },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'latestTimestamp';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'maxDelay';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'maximumSnapshotAge';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint48'; readonly internalType: 'uint48' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'minimumSnapshotDelay';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint48'; readonly internalType: 'uint48' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'owner';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'pendingOwner';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'renounceOwnership';
      readonly inputs: readonly [];
      readonly outputs: readonly [];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'setGrowthCapBounds';
      readonly inputs: readonly [
        {
          readonly name: 'maxAnnualGrowthBps';
          readonly type: 'uint16';
          readonly internalType: 'uint16';
        },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'setKeeper';
      readonly inputs: readonly [
        { readonly name: 'newKeeper'; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'setRejectionGraceBps';
      readonly inputs: readonly [
        {
          readonly name: 'rejectionGraceBps';
          readonly type: 'uint16';
          readonly internalType: 'uint16';
        },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'sharesContract';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'address'; readonly internalType: 'contract IERC4626' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'sharesDecimals';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint8'; readonly internalType: 'uint8' },
      ];
      readonly stateMutability: 'view';
    },
    {
      readonly type: 'function';
      readonly name: 'transferOwnership';
      readonly inputs: readonly [
        { readonly name: 'newOwner'; readonly type: 'address'; readonly internalType: 'address' },
      ];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'updateSnapshot';
      readonly inputs: readonly [];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'updateSnapshotImmediate';
      readonly inputs: readonly [];
      readonly outputs: readonly [];
      readonly stateMutability: 'nonpayable';
    },
    {
      readonly type: 'function';
      readonly name: 'version';
      readonly inputs: readonly [];
      readonly outputs: readonly [
        { readonly name: ''; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
      readonly stateMutability: 'pure';
    },
    {
      readonly type: 'event';
      readonly name: 'AnswerUpdated';
      readonly inputs: readonly [
        {
          readonly name: 'current';
          readonly type: 'int256';
          readonly indexed: true;
          readonly internalType: 'int256';
        },
        {
          readonly name: 'roundId';
          readonly type: 'uint256';
          readonly indexed: true;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'updatedAt';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'GrowthCapBoundsUpdated';
      readonly inputs: readonly [
        {
          readonly name: 'maxAnnualGrowthBps';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'growthRatePerSecond';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'KeeperUpdated';
      readonly inputs: readonly [
        {
          readonly name: 'previousKeeper';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'newKeeper';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'NewRound';
      readonly inputs: readonly [
        {
          readonly name: 'roundId';
          readonly type: 'uint256';
          readonly indexed: true;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'startedBy';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'startedAt';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'OwnershipTransferStarted';
      readonly inputs: readonly [
        {
          readonly name: 'previousOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'newOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'OwnershipTransferred';
      readonly inputs: readonly [
        {
          readonly name: 'previousOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
        {
          readonly name: 'newOwner';
          readonly type: 'address';
          readonly indexed: true;
          readonly internalType: 'address';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'RejectionGraceUpdated';
      readonly inputs: readonly [
        {
          readonly name: 'previousRejectionGraceBps';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'newRejectionGraceBps';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'SnapshotActivated';
      readonly inputs: readonly [
        {
          readonly name: 'snapshotRatio';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'effectiveAt';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    {
      readonly type: 'event';
      readonly name: 'SnapshotQueued';
      readonly inputs: readonly [
        {
          readonly name: 'snapshotRatio';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
        {
          readonly name: 'effectiveAt';
          readonly type: 'uint256';
          readonly indexed: false;
          readonly internalType: 'uint256';
        },
      ];
      readonly anonymous: false;
    },
    { readonly type: 'error'; readonly name: 'AddressZero'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'InvalidBasePrice'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'InvalidDecimals'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'InvalidGrowthRate'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'InvalidKeeper'; readonly inputs: readonly [] },
    {
      readonly type: 'error';
      readonly name: 'InvalidRejectionGrace';
      readonly inputs: readonly [];
    },
    {
      readonly type: 'error';
      readonly name: 'InvalidSharesConversion';
      readonly inputs: readonly [];
    },
    { readonly type: 'error'; readonly name: 'InvalidSnapshotRatio'; readonly inputs: readonly [] },
    {
      readonly type: 'error';
      readonly name: 'InvalidSnapshotTimestamp';
      readonly inputs: readonly [];
    },
    { readonly type: 'error'; readonly name: 'OwnershipRequired'; readonly inputs: readonly [] },
    {
      readonly type: 'error';
      readonly name: 'PriceTooOld';
      readonly inputs: readonly [
        {
          readonly name: 'currentTime';
          readonly type: 'uint256';
          readonly internalType: 'uint256';
        },
        { readonly name: 'updatedAt'; readonly type: 'uint256'; readonly internalType: 'uint256' },
        { readonly name: 'maxTime'; readonly type: 'uint256'; readonly internalType: 'uint256' },
      ];
    },
    { readonly type: 'error'; readonly name: 'SameAddress'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'SnapshotTooOld'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'SnapshotTooRecent'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'StaleRound'; readonly inputs: readonly [] },
    { readonly type: 'error'; readonly name: 'UnauthorizedAccess'; readonly inputs: readonly [] },
  ] satisfies Abi;
