cacheFolder: .yarn/cache

enableGlobalCache: false

enableHardenedMode: true

enableImmutableInstalls: true

enableInlineBuilds: true

enableInlineHunks: true

enableScripts: true

enableStrictSsl: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

progressBarStyle: patrick
