import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';

const args = process.argv.slice(2);
let root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
let check = false;
let importSource;
let artifactRoot;
while (args.length) {
  const flag = args.shift();
  if (flag === '--root' && args[0]) root = resolve(args.shift());
  else if (flag === '--check') check = true;
  else if (flag === '--import' && args.length >= 2) {
    importSource = args.shift();
    artifactRoot = resolve(args.shift());
  } else throw new Error(`Unknown or incomplete option: ${flag}`);
}
if (check && importSource) throw new Error('--check cannot import or change ABI files.');

const provenancePath = join(root, 'abi-provenance.json');
const provenance = JSON.parse(await readFile(provenancePath, 'utf8'));
const config = (await resolveConfig(fileURLToPath(import.meta.url))) ?? {};
const generated = '// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.\n';
const hash = abi => createHash('sha256').update(JSON.stringify(abi)).digest('hex');
const abiPath = entry => join(root, 'src/abis', `${entry.export}.json`);
const assertAbi = abi => {
  if (!Array.isArray(abi) || !abi.length || abi.some(item => !item || !item.type)) {
    throw new Error('Expected a complete ABI array.');
  }
};
const entries = provenance.abis;
const names = new Set();
for (const entry of entries) {
  if (!/^[a-z][A-Za-z0-9]*Abi$/.test(entry.export) || names.has(entry.export)) {
    throw new Error(`Invalid or duplicate export: ${entry.export}`);
  }
  if (!/^[A-Z][A-Za-z0-9]*Abi$/.test(entry.typeName) || !provenance.sources[entry.source]) {
    throw new Error(`Invalid type or source: ${entry.export}`);
  }
  names.add(entry.export);
}
for (const [alias, target] of Object.entries(provenance.aliases ?? {})) {
  if (!/^[a-z][A-Za-z0-9]*Abi$/.test(alias) || names.has(alias) || !names.has(target)) {
    throw new Error(`Invalid alias: ${alias}`);
  }
  names.add(alias);
}

if (importSource) {
  const selected = entries.filter(entry => entry.source === importSource);
  if (!selected.length) throw new Error(`Unknown or empty source: ${importSource}`);
  // Read and validate the entire source batch before changing any snapshot.
  const imports = await Promise.all(
    selected.map(async entry => {
      if (!entry.artifact) throw new Error(`No compiled artifact recorded for ${entry.export}`);
      const artifact = JSON.parse(await readFile(join(artifactRoot, entry.artifact), 'utf8'));
      assertAbi(artifact.abi);
      return { entry, abi: artifact.abi };
    }),
  );
  for (const { entry, abi } of imports) {
    await writeFile(
      abiPath(entry),
      await format(JSON.stringify(abi), { ...config, parser: 'json' }),
    );
    entry.sha256 = hash(abi);
    entry.entries = Object.fromEntries(
      ['constructor', 'function', 'event', 'error'].map(type => [
        type,
        abi.filter(item => item.type === type).length,
      ]),
    );
  }
  await writeFile(
    provenancePath,
    await format(JSON.stringify(provenance), { ...config, parser: 'json' }),
  );
}

// A generated readonly literal type retains every ABI value while the runtime imports JSON once.
const literalType = value => {
  if (Array.isArray(value)) return `readonly [${value.map(literalType).join(',')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.entries(value)
      .map(([key, item]) => `readonly ${JSON.stringify(key)}: ${literalType(item)};`)
      .join('')}}`;
  }
  return JSON.stringify(value);
};
const outputs = [];
for (const entry of entries) {
  const abi = JSON.parse(await readFile(abiPath(entry), 'utf8'));
  assertAbi(abi);
  if (hash(abi) !== entry.sha256) throw new Error(`ABI differs from provenance: ${entry.export}`);
  outputs.push({
    path: join(root, 'src/abis', `${entry.export}.ts`),
    text:
      `${generated}import type { Abi } from 'abitype';\n` +
      `import ${entry.export}Json from './${entry.export}.json';\n\n` +
      `export const ${entry.export} = ${entry.export}Json as unknown as ${literalType(abi)} satisfies Abi;\n`,
  });
}
const aliases = Object.entries(provenance.aliases ?? {});
outputs.push({
  path: join(root, 'src/abis/index.ts'),
  text:
    generated +
    entries.map(entry => `export { ${entry.export} } from './${entry.export}';\n`).join('') +
    aliases
      .map(([alias, target]) => `export { ${target} as ${alias} } from './${target}';\n`)
      .join(''),
});
outputs.push({
  path: join(root, 'src/types.ts'),
  text:
    `${generated}import type * as abis from './abis';\n\n` +
    `export type { ContractFunctionName, ContractFunctionArgs, ContractFunctionReturnType, ContractEventName, ContractEventArgs, ContractEventArgsFromTopics, ContractConstructorArgs, ContractErrorName, ContractErrorArgs } from 'viem';\n\n` +
    entries
      .map(entry => `export type ${entry.typeName} = typeof abis.${entry.export};\n`)
      .join('') +
    aliases
      .map(
        ([alias]) =>
          `export type ${alias[0].toUpperCase() + alias.slice(1)} = typeof abis.${alias};\n`,
      )
      .join(''),
});

const stale = [];
for (const output of outputs) {
  const formatted = await format(output.text, { ...config, parser: 'typescript' });
  if (check) {
    const current = await readFile(output.path, 'utf8').catch(() => '');
    if (current !== formatted) stale.push(output.path);
  } else await writeFile(output.path, formatted);
}
if (stale.length)
  throw new Error(`Stale ABI exports. Run yarn generate:abis:\n${stale.join('\n')}`);
console.log(
  `${check ? 'Checked' : 'Generated'} ${entries.length} ABIs and ${aliases.length} aliases.`,
);
