// Generated by yarn generate:abis. Edit the ABI JSON and provenance instead.
import type * as abis from './abis';

export type {
  ContractFunctionName,
  ContractFunctionArgs,
  ContractFunctionReturnType,
  ContractEventName,
  ContractEventArgs,
  ContractEventArgsFromTopics,
  ContractConstructorArgs,
  ContractErrorName,
  ContractErrorArgs,
} from 'viem';

export type ATokenAbi = typeof abis.aTokenAbi;
export type AaveOracleAbi = typeof abis.aaveOracleAbi;
export type AaveProtocolDataProviderAbi = typeof abis.aaveProtocolDataProviderAbi;
export type AclManagerAbi = typeof abis.aclManagerAbi;
export type DefaultReserveInterestRateStrategyAbi =
  typeof abis.defaultReserveInterestRateStrategyAbi;
export type DustAbi = typeof abis.dustAbi;
export type DustLockAbi = typeof abis.dustLockAbi;
export type DustLockLegendaryLedgerAbi = typeof abis.dustLockLegendaryLedgerAbi;
export type DustLockTransferStrategyAbi = typeof abis.dustLockTransferStrategyAbi;
export type DustRewardsControllerAbi = typeof abis.dustRewardsControllerAbi;
export type EpochManagerAbi = typeof abis.epochManagerAbi;
export type Erc20Abi = typeof abis.erc20Abi;
export type Erc4626Abi = typeof abis.erc4626Abi;
export type GovernedPriceOracleAbi = typeof abis.governedPriceOracleAbi;
export type HardcodedPriceOracleAbi = typeof abis.hardcodedPriceOracleAbi;
export type LeaderboardConfigAbi = typeof abis.leaderboardConfigAbi;
export type LeaderboardKeeperAbi = typeof abis.leaderboardKeeperAbi;
export type MarketHoursPriceAdapterAbi = typeof abis.marketHoursPriceAdapterAbi;
export type MarketHoursSentinelAbi = typeof abis.marketHoursSentinelAbi;
export type Multicall3Abi = typeof abis.multicall3Abi;
export type NeverlandAssetRedemptionAbi = typeof abis.neverlandAssetRedemptionAbi;
export type NeverlandDustHelperAbi = typeof abis.neverlandDustHelperAbi;
export type NeverlandNativeGatewayAbi = typeof abis.neverlandNativeGatewayAbi;
export type NeverlandPendleLeveragerAbi = typeof abis.neverlandPendleLeveragerAbi;
export type NeverlandPendleMaturityGatewayAbi = typeof abis.neverlandPendleMaturityGatewayAbi;
export type NeverlandProfileItemsSellerAbi = typeof abis.neverlandProfileItemsSellerAbi;
export type NeverlandTimelockControllerAbi = typeof abis.neverlandTimelockControllerAbi;
export type NeverlandUiProviderAbi = typeof abis.neverlandUiProviderAbi;
export type NftPartnershipRegistryAbi = typeof abis.nftPartnershipRegistryAbi;
export type PendlePtDiscountOracleAdapterAbi = typeof abis.pendlePtDiscountOracleAdapterAbi;
export type PoolAbi = typeof abis.poolAbi;
export type PoolAddressesProviderAbi = typeof abis.poolAddressesProviderAbi;
export type PoolAddressesProviderRegistryAbi = typeof abis.poolAddressesProviderRegistryAbi;
export type PoolConfiguratorAbi = typeof abis.poolConfiguratorAbi;
export type RatioOracleAggregatorAbi = typeof abis.ratioOracleAggregatorAbi;
export type RevenueRewardAbi = typeof abis.revenueRewardAbi;
export type SessionCalendarAbi = typeof abis.sessionCalendarAbi;
export type SpecialEditionRegistryAbi = typeof abis.specialEditionRegistryAbi;
export type StableDebtTokenAbi = typeof abis.stableDebtTokenAbi;
export type StataOracleAbi = typeof abis.stataOracleAbi;
export type StaticATokenFactoryAbi = typeof abis.staticATokenFactoryAbi;
export type StaticATokenLMAbi = typeof abis.staticATokenLMAbi;
export type UiIncentiveDataProviderV3Abi = typeof abis.uiIncentiveDataProviderV3Abi;
export type UiPoolDataProviderV3Abi = typeof abis.uiPoolDataProviderV3Abi;
export type UserVaultAbi = typeof abis.userVaultAbi;
export type UserVaultFactoryAbi = typeof abis.userVaultFactoryAbi;
export type UserVaultRegistryAbi = typeof abis.userVaultRegistryAbi;
export type VariableDebtTokenAbi = typeof abis.variableDebtTokenAbi;
export type VotingPowerMultiplierAbi = typeof abis.votingPowerMultiplierAbi;
export type WalletBalanceProviderAbi = typeof abis.walletBalanceProviderAbi;
export type WethGatewayLegacyAbi = typeof abis.wethGatewayLegacyAbi;
export type WrappedTokenGatewayV3Abi = typeof abis.wrappedTokenGatewayV3Abi;
export type YieldBearingOracleAdapterAbi = typeof abis.yieldBearingOracleAdapterAbi;
export type DustLockLegendaryGatewayAbi = typeof abis.dustLockLegendaryGatewayAbi;
export type StaticATokenAbi = typeof abis.staticATokenAbi;
